package bitaxe

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestSystemInfo(t *testing.T) {
	fd, err := os.Open(filepath.Join("..", "..", "testdata", "api", "system-info.json"))
	require.NoError(t, err)

	t.Cleanup(func() { fd.Close() })

	dec := json.NewDecoder(fd)
	dec.DisallowUnknownFields()

	var info SystemInfo
	err = dec.Decode(&info)
	require.NoError(t, err)

	require.InDelta(t, 23.6954327, info.Power, 0.01)
	require.InDelta(t, 5007.8125, info.Voltage, 0.01)
	require.InDelta(t, 15640.625, info.Current, 0.01)
	require.InDelta(t, 59.75, info.Temp, 0.01)
	require.Equal(t, -1, info.Temp2)
	require.Equal(t, 67, info.VrTemp)
	require.Equal(t, 40, info.MaxPower)
	require.Equal(t, 5, info.NominalVoltage)
	require.InDelta(t, 1234.3735352, info.HashRate, 0.01)
	require.InDelta(t, 1223.206665, info.HashRate1m, 0.01)
	require.InDelta(t, 1223.7230225, info.HashRate10m, 0.01)
	require.InDelta(t, 1226.1037598, info.HashRate1h, 0.01)
	require.Equal(t, 1224, info.ExpectedHashrate)
	require.InDelta(t, 0.1391789, info.ErrorPercentage, 0.01)
	require.InDelta(t, 3468978118.0, info.BestDiff, 0.01)
	require.InDelta(t, 13120897.0, info.BestSessionDiff, 0.01)
	require.Equal(t, 1000, info.PoolDifficulty)
	require.Equal(t, 0, info.IsUsingFallbackStratum)
	// require.Equal(t, 2, info.PoolAddrFamily) // TODO(adam): https://github.com/bitaxeorg/ESP-Miner/issues/1493
	require.Equal(t, 1, info.IsPSRAMAvailable)
	require.Equal(t, 8165372, info.FreeHeap)
	require.Equal(t, 103467, info.FreeHeapInternal)
	require.Equal(t, 8093876, info.FreeHeapSpiram)
	require.Equal(t, 1200, info.CoreVoltage)
	require.Equal(t, 1195, info.CoreVoltageActual)
	require.Equal(t, 600, info.Frequency)
	require.Equal(t, "RightOnTarget", info.Ssid)
	require.Equal(t, "D8:3B:DA:6E:C0:D0", info.MacAddr)
	require.Equal(t, "bitaxe_C0D1", info.Hostname)
	require.Equal(t, "192.168.12.100", info.Ipv4)
	require.Equal(t, "FD6D:FD25:2174:0:DA3B:DAFF:FE6E:C0D0", info.Ipv6)
	require.Equal(t, "Connected!", info.WifiStatus)
	require.Equal(t, -48, info.WifiRSSI)
	require.Equal(t, 0, info.ApEnabled)
	require.Equal(t, 20773, info.SharesAccepted)
	require.Equal(t, 0, info.SharesRejected)
	require.Empty(t, info.SharesRejectedReasons)
	require.Equal(t, 72227, info.UptimeSeconds)
	require.Equal(t, 2040, info.SmallCoreCount)
	require.Equal(t, "BM1370", info.ASICModel)
	require.Equal(t, "test.hydrapool.org", info.StratumURL)
	require.Equal(t, 3333, info.StratumPort)
	require.Equal(t, "bc1qsyz6ehyjqzfs478un8vyks9l3mfwn26alqh6fs.HardestBlocksDotOrg", info.StratumUser)
	require.Equal(t, 1000, info.StratumSuggestedDifficulty)
	require.Equal(t, 0, info.StratumExtranonceSubscribe)
	require.Equal(t, "solo.ckpool.org", info.FallbackStratumURL)
	require.Equal(t, 3333, info.FallbackStratumPort)
	require.Equal(t, "bc1qsyz6ehyjqzfs478un8vyks9l3mfwn26alqh6fs.bitaxe", info.FallbackStratumUser)
	require.Equal(t, 1000, info.FallbackStratumSuggestedDifficulty)
	require.Equal(t, 0, info.FallbackStratumExtranonceSubscribe)
	require.InDelta(t, 146.915, info.ResponseTime, 0.01)
	require.Equal(t, "v2.12.0", info.Version)
	require.Equal(t, "v2.12.0", info.AxeOSVersion)
	require.Equal(t, "v5.5.1", info.IdfVersion)
	require.Equal(t, "601", info.BoardVersion)
	require.Equal(t, "Reset due to power-on event", info.ResetReason)
	require.Equal(t, "ota_1", info.RunningPartition)
	require.Equal(t, 0, info.OverheatMode)
	require.Equal(t, 0, info.OverclockEnabled)
	require.Equal(t, "SSD1306 (128x32)", info.Display)
	require.Equal(t, 0, info.Rotation)
	require.Equal(t, 0, info.Invertscreen)
	require.Equal(t, 1, info.DisplayTimeout)
	require.Equal(t, 1, info.Autofanspeed)
	require.InDelta(t, 42.9381981, info.Fanspeed, 0.01)
	require.Equal(t, 51, info.ManualFanSpeed)
	require.Equal(t, 25, info.MinFanSpeed)
	require.Equal(t, 60, info.Temptarget)
	require.Equal(t, 4415, info.Fanrpm)
	require.Equal(t, 0, info.Fan2rpm)
	require.Equal(t, 60, info.StatsFrequency)
	require.Equal(t, 0, info.BlockFound)
	require.Equal(t, 931037, info.BlockHeight)
	require.Equal(t, "...d.\\i..3.6..hydrapool", info.Scriptsig)
	require.InDelta(t, 148258433855481.0, info.NetworkDifficulty, 0.01)
	require.Len(t, info.HashrateMonitor.Asics, 1)
	require.InDelta(t, 1234.3735352, info.HashrateMonitor.Asics[0].Total, 0.01)
	require.InDeltaSlice(t, []float64{307.5196533, 300.6477051, 314.3916016, 312.673645}, info.HashrateMonitor.Asics[0].Domains, 0.01)
	require.Equal(t, 59635, info.HashrateMonitor.Asics[0].ErrorCount)
}
