/*
ESP-Miner API

API specification for ESP-Miner HTTP server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WifiNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WifiNetwork{}

// WifiNetwork struct for WifiNetwork
type WifiNetwork struct {
	// Network SSID
	Ssid string `json:"ssid"`
	// Signal strength in dBm
	Rssi int32 `json:"rssi"`
	// Authentication mode: * 0 - OPEN * 1 - WEP * 2 - WPA_PSK * 3 - WPA2_PSK * 4 - WPA_WPA2_PSK * 5 - WPA2_ENTERPRISE * 6 - WPA3_PSK * 7 - WPA2_WPA3_PSK * 8 - WAPI_PSK * 9 - OWE (Opportunistic Wireless Encryption) * 10 - WPA3_ENT_192 (Enterprise Suite-B) * 11 - WPA3_PSK_192 (deprecated, use WPA3_PSK) * 12 - WPA3_EXT_PSK (deprecated, use WPA3_PSK) 
	Authmode int32 `json:"authmode"`
}

type _WifiNetwork WifiNetwork

// NewWifiNetwork instantiates a new WifiNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWifiNetwork(ssid string, rssi int32, authmode int32) *WifiNetwork {
	this := WifiNetwork{}
	this.Ssid = ssid
	this.Rssi = rssi
	this.Authmode = authmode
	return &this
}

// NewWifiNetworkWithDefaults instantiates a new WifiNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWifiNetworkWithDefaults() *WifiNetwork {
	this := WifiNetwork{}
	return &this
}

// GetSsid returns the Ssid field value
func (o *WifiNetwork) GetSsid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ssid
}

// GetSsidOk returns a tuple with the Ssid field value
// and a boolean to check if the value has been set.
func (o *WifiNetwork) GetSsidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ssid, true
}

// SetSsid sets field value
func (o *WifiNetwork) SetSsid(v string) {
	o.Ssid = v
}

// GetRssi returns the Rssi field value
func (o *WifiNetwork) GetRssi() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rssi
}

// GetRssiOk returns a tuple with the Rssi field value
// and a boolean to check if the value has been set.
func (o *WifiNetwork) GetRssiOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rssi, true
}

// SetRssi sets field value
func (o *WifiNetwork) SetRssi(v int32) {
	o.Rssi = v
}

// GetAuthmode returns the Authmode field value
func (o *WifiNetwork) GetAuthmode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Authmode
}

// GetAuthmodeOk returns a tuple with the Authmode field value
// and a boolean to check if the value has been set.
func (o *WifiNetwork) GetAuthmodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authmode, true
}

// SetAuthmode sets field value
func (o *WifiNetwork) SetAuthmode(v int32) {
	o.Authmode = v
}

func (o WifiNetwork) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WifiNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ssid"] = o.Ssid
	toSerialize["rssi"] = o.Rssi
	toSerialize["authmode"] = o.Authmode
	return toSerialize, nil
}

func (o *WifiNetwork) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ssid",
		"rssi",
		"authmode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWifiNetwork := _WifiNetwork{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWifiNetwork)

	if err != nil {
		return err
	}

	*o = WifiNetwork(varWifiNetwork)

	return err
}

type NullableWifiNetwork struct {
	value *WifiNetwork
	isSet bool
}

func (v NullableWifiNetwork) Get() *WifiNetwork {
	return v.value
}

func (v *NullableWifiNetwork) Set(val *WifiNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableWifiNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableWifiNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWifiNetwork(val *WifiNetwork) *NullableWifiNetwork {
	return &NullableWifiNetwork{value: val, isSet: true}
}

func (v NullableWifiNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWifiNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


