/*
ESP-Miner API

API specification for ESP-Miner HTTP server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Settings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Settings{}

// Settings struct for Settings
type Settings struct {
	// Forces the use the fallback stratum pool
	UseFallbackStratum *float32 `json:"useFallbackStratum,omitempty"`
	// Primary stratum server URL
	StratumURL *string `json:"stratumURL,omitempty"`
	// Fallback stratum server URL used when primary is unavailable
	FallbackStratumURL *string `json:"fallbackStratumURL,omitempty"`
	// Username for primary stratum server
	StratumUser *string `json:"stratumUser,omitempty"`
	// Password for primary stratum server
	StratumPassword *string `json:"stratumPassword,omitempty"`
	// Username for fallback stratum server
	FallbackStratumUser *string `json:"fallbackStratumUser,omitempty"`
	// Password for fallback stratum server
	FallbackStratumPassword *string `json:"fallbackStratumPassword,omitempty"`
	// Port number for primary stratum server
	StratumPort *int32 `json:"stratumPort,omitempty"`
	// Port number for fallback stratum server
	FallbackStratumPort *int32 `json:"fallbackStratumPort,omitempty"`
	// WiFi network SSID
	Ssid *string `json:"ssid,omitempty"`
	// WiFi network password
	WifiPass *string `json:"wifiPass,omitempty"`
	// Device hostname
	Hostname *string `json:"hostname,omitempty" validate:"regexp=^[a-zA-Z0-9-]+$"`
	// ASIC core voltage in millivolts
	CoreVoltage *int32 `json:"coreVoltage,omitempty"`
	// ASIC frequency in MHz
	Frequency *int32 `json:"frequency,omitempty"`
	// Whether to rotate the screen orientation (0, 90, 180, 270 degrees)
	Rotation *int32 `json:"rotation,omitempty"`
	// Overheat protection mode (0=disabled)
	OverheatMode *int32 `json:"overheat_mode,omitempty"`
	// Set custom voltage/frequency in AxeOS (0=disabled, 1=enabled)
	OverclockEnabled *int32 `json:"overclockEnabled,omitempty"`
	// Whether to invert screen colors (0=normal, 1=inverted)
	Invertscreen *int32 `json:"invertscreen,omitempty"`
	// Whether to enable automatic fan speed control (0=manual, 1=auto)
	Autofanspeed *int32 `json:"autofanspeed,omitempty"`
	// Manual fan speed percentage when autofanspeed is disabled
	Fanspeed *int32 `json:"fanspeed,omitempty"`
	// Manual Temperature Target in °C when autofanspeed is enabled
	Temptarget *int32 `json:"temptarget,omitempty"`
	// Set display timeout time in minutes (-1=display on, 0=display off)
	DisplayTimeout *int32 `json:"displayTimeout,omitempty"`
	// Set statistics frequency in seconds (0=disabled)
	StatsFrequency *int32 `json:"statsFrequency,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Settings Settings

// NewSettings instantiates a new Settings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettings() *Settings {
	this := Settings{}
	return &this
}

// NewSettingsWithDefaults instantiates a new Settings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsWithDefaults() *Settings {
	this := Settings{}
	return &this
}

// GetUseFallbackStratum returns the UseFallbackStratum field value if set, zero value otherwise.
func (o *Settings) GetUseFallbackStratum() float32 {
	if o == nil || IsNil(o.UseFallbackStratum) {
		var ret float32
		return ret
	}
	return *o.UseFallbackStratum
}

// GetUseFallbackStratumOk returns a tuple with the UseFallbackStratum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetUseFallbackStratumOk() (*float32, bool) {
	if o == nil || IsNil(o.UseFallbackStratum) {
		return nil, false
	}
	return o.UseFallbackStratum, true
}

// HasUseFallbackStratum returns a boolean if a field has been set.
func (o *Settings) HasUseFallbackStratum() bool {
	if o != nil && !IsNil(o.UseFallbackStratum) {
		return true
	}

	return false
}

// SetUseFallbackStratum gets a reference to the given float32 and assigns it to the UseFallbackStratum field.
func (o *Settings) SetUseFallbackStratum(v float32) {
	o.UseFallbackStratum = &v
}

// GetStratumURL returns the StratumURL field value if set, zero value otherwise.
func (o *Settings) GetStratumURL() string {
	if o == nil || IsNil(o.StratumURL) {
		var ret string
		return ret
	}
	return *o.StratumURL
}

// GetStratumURLOk returns a tuple with the StratumURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetStratumURLOk() (*string, bool) {
	if o == nil || IsNil(o.StratumURL) {
		return nil, false
	}
	return o.StratumURL, true
}

// HasStratumURL returns a boolean if a field has been set.
func (o *Settings) HasStratumURL() bool {
	if o != nil && !IsNil(o.StratumURL) {
		return true
	}

	return false
}

// SetStratumURL gets a reference to the given string and assigns it to the StratumURL field.
func (o *Settings) SetStratumURL(v string) {
	o.StratumURL = &v
}

// GetFallbackStratumURL returns the FallbackStratumURL field value if set, zero value otherwise.
func (o *Settings) GetFallbackStratumURL() string {
	if o == nil || IsNil(o.FallbackStratumURL) {
		var ret string
		return ret
	}
	return *o.FallbackStratumURL
}

// GetFallbackStratumURLOk returns a tuple with the FallbackStratumURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetFallbackStratumURLOk() (*string, bool) {
	if o == nil || IsNil(o.FallbackStratumURL) {
		return nil, false
	}
	return o.FallbackStratumURL, true
}

// HasFallbackStratumURL returns a boolean if a field has been set.
func (o *Settings) HasFallbackStratumURL() bool {
	if o != nil && !IsNil(o.FallbackStratumURL) {
		return true
	}

	return false
}

// SetFallbackStratumURL gets a reference to the given string and assigns it to the FallbackStratumURL field.
func (o *Settings) SetFallbackStratumURL(v string) {
	o.FallbackStratumURL = &v
}

// GetStratumUser returns the StratumUser field value if set, zero value otherwise.
func (o *Settings) GetStratumUser() string {
	if o == nil || IsNil(o.StratumUser) {
		var ret string
		return ret
	}
	return *o.StratumUser
}

// GetStratumUserOk returns a tuple with the StratumUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetStratumUserOk() (*string, bool) {
	if o == nil || IsNil(o.StratumUser) {
		return nil, false
	}
	return o.StratumUser, true
}

// HasStratumUser returns a boolean if a field has been set.
func (o *Settings) HasStratumUser() bool {
	if o != nil && !IsNil(o.StratumUser) {
		return true
	}

	return false
}

// SetStratumUser gets a reference to the given string and assigns it to the StratumUser field.
func (o *Settings) SetStratumUser(v string) {
	o.StratumUser = &v
}

// GetStratumPassword returns the StratumPassword field value if set, zero value otherwise.
func (o *Settings) GetStratumPassword() string {
	if o == nil || IsNil(o.StratumPassword) {
		var ret string
		return ret
	}
	return *o.StratumPassword
}

// GetStratumPasswordOk returns a tuple with the StratumPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetStratumPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.StratumPassword) {
		return nil, false
	}
	return o.StratumPassword, true
}

// HasStratumPassword returns a boolean if a field has been set.
func (o *Settings) HasStratumPassword() bool {
	if o != nil && !IsNil(o.StratumPassword) {
		return true
	}

	return false
}

// SetStratumPassword gets a reference to the given string and assigns it to the StratumPassword field.
func (o *Settings) SetStratumPassword(v string) {
	o.StratumPassword = &v
}

// GetFallbackStratumUser returns the FallbackStratumUser field value if set, zero value otherwise.
func (o *Settings) GetFallbackStratumUser() string {
	if o == nil || IsNil(o.FallbackStratumUser) {
		var ret string
		return ret
	}
	return *o.FallbackStratumUser
}

// GetFallbackStratumUserOk returns a tuple with the FallbackStratumUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetFallbackStratumUserOk() (*string, bool) {
	if o == nil || IsNil(o.FallbackStratumUser) {
		return nil, false
	}
	return o.FallbackStratumUser, true
}

// HasFallbackStratumUser returns a boolean if a field has been set.
func (o *Settings) HasFallbackStratumUser() bool {
	if o != nil && !IsNil(o.FallbackStratumUser) {
		return true
	}

	return false
}

// SetFallbackStratumUser gets a reference to the given string and assigns it to the FallbackStratumUser field.
func (o *Settings) SetFallbackStratumUser(v string) {
	o.FallbackStratumUser = &v
}

// GetFallbackStratumPassword returns the FallbackStratumPassword field value if set, zero value otherwise.
func (o *Settings) GetFallbackStratumPassword() string {
	if o == nil || IsNil(o.FallbackStratumPassword) {
		var ret string
		return ret
	}
	return *o.FallbackStratumPassword
}

// GetFallbackStratumPasswordOk returns a tuple with the FallbackStratumPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetFallbackStratumPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.FallbackStratumPassword) {
		return nil, false
	}
	return o.FallbackStratumPassword, true
}

// HasFallbackStratumPassword returns a boolean if a field has been set.
func (o *Settings) HasFallbackStratumPassword() bool {
	if o != nil && !IsNil(o.FallbackStratumPassword) {
		return true
	}

	return false
}

// SetFallbackStratumPassword gets a reference to the given string and assigns it to the FallbackStratumPassword field.
func (o *Settings) SetFallbackStratumPassword(v string) {
	o.FallbackStratumPassword = &v
}

// GetStratumPort returns the StratumPort field value if set, zero value otherwise.
func (o *Settings) GetStratumPort() int32 {
	if o == nil || IsNil(o.StratumPort) {
		var ret int32
		return ret
	}
	return *o.StratumPort
}

// GetStratumPortOk returns a tuple with the StratumPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetStratumPortOk() (*int32, bool) {
	if o == nil || IsNil(o.StratumPort) {
		return nil, false
	}
	return o.StratumPort, true
}

// HasStratumPort returns a boolean if a field has been set.
func (o *Settings) HasStratumPort() bool {
	if o != nil && !IsNil(o.StratumPort) {
		return true
	}

	return false
}

// SetStratumPort gets a reference to the given int32 and assigns it to the StratumPort field.
func (o *Settings) SetStratumPort(v int32) {
	o.StratumPort = &v
}

// GetFallbackStratumPort returns the FallbackStratumPort field value if set, zero value otherwise.
func (o *Settings) GetFallbackStratumPort() int32 {
	if o == nil || IsNil(o.FallbackStratumPort) {
		var ret int32
		return ret
	}
	return *o.FallbackStratumPort
}

// GetFallbackStratumPortOk returns a tuple with the FallbackStratumPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetFallbackStratumPortOk() (*int32, bool) {
	if o == nil || IsNil(o.FallbackStratumPort) {
		return nil, false
	}
	return o.FallbackStratumPort, true
}

// HasFallbackStratumPort returns a boolean if a field has been set.
func (o *Settings) HasFallbackStratumPort() bool {
	if o != nil && !IsNil(o.FallbackStratumPort) {
		return true
	}

	return false
}

// SetFallbackStratumPort gets a reference to the given int32 and assigns it to the FallbackStratumPort field.
func (o *Settings) SetFallbackStratumPort(v int32) {
	o.FallbackStratumPort = &v
}

// GetSsid returns the Ssid field value if set, zero value otherwise.
func (o *Settings) GetSsid() string {
	if o == nil || IsNil(o.Ssid) {
		var ret string
		return ret
	}
	return *o.Ssid
}

// GetSsidOk returns a tuple with the Ssid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetSsidOk() (*string, bool) {
	if o == nil || IsNil(o.Ssid) {
		return nil, false
	}
	return o.Ssid, true
}

// HasSsid returns a boolean if a field has been set.
func (o *Settings) HasSsid() bool {
	if o != nil && !IsNil(o.Ssid) {
		return true
	}

	return false
}

// SetSsid gets a reference to the given string and assigns it to the Ssid field.
func (o *Settings) SetSsid(v string) {
	o.Ssid = &v
}

// GetWifiPass returns the WifiPass field value if set, zero value otherwise.
func (o *Settings) GetWifiPass() string {
	if o == nil || IsNil(o.WifiPass) {
		var ret string
		return ret
	}
	return *o.WifiPass
}

// GetWifiPassOk returns a tuple with the WifiPass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetWifiPassOk() (*string, bool) {
	if o == nil || IsNil(o.WifiPass) {
		return nil, false
	}
	return o.WifiPass, true
}

// HasWifiPass returns a boolean if a field has been set.
func (o *Settings) HasWifiPass() bool {
	if o != nil && !IsNil(o.WifiPass) {
		return true
	}

	return false
}

// SetWifiPass gets a reference to the given string and assigns it to the WifiPass field.
func (o *Settings) SetWifiPass(v string) {
	o.WifiPass = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *Settings) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *Settings) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *Settings) SetHostname(v string) {
	o.Hostname = &v
}

// GetCoreVoltage returns the CoreVoltage field value if set, zero value otherwise.
func (o *Settings) GetCoreVoltage() int32 {
	if o == nil || IsNil(o.CoreVoltage) {
		var ret int32
		return ret
	}
	return *o.CoreVoltage
}

// GetCoreVoltageOk returns a tuple with the CoreVoltage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetCoreVoltageOk() (*int32, bool) {
	if o == nil || IsNil(o.CoreVoltage) {
		return nil, false
	}
	return o.CoreVoltage, true
}

// HasCoreVoltage returns a boolean if a field has been set.
func (o *Settings) HasCoreVoltage() bool {
	if o != nil && !IsNil(o.CoreVoltage) {
		return true
	}

	return false
}

// SetCoreVoltage gets a reference to the given int32 and assigns it to the CoreVoltage field.
func (o *Settings) SetCoreVoltage(v int32) {
	o.CoreVoltage = &v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *Settings) GetFrequency() int32 {
	if o == nil || IsNil(o.Frequency) {
		var ret int32
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetFrequencyOk() (*int32, bool) {
	if o == nil || IsNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *Settings) HasFrequency() bool {
	if o != nil && !IsNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given int32 and assigns it to the Frequency field.
func (o *Settings) SetFrequency(v int32) {
	o.Frequency = &v
}

// GetRotation returns the Rotation field value if set, zero value otherwise.
func (o *Settings) GetRotation() int32 {
	if o == nil || IsNil(o.Rotation) {
		var ret int32
		return ret
	}
	return *o.Rotation
}

// GetRotationOk returns a tuple with the Rotation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetRotationOk() (*int32, bool) {
	if o == nil || IsNil(o.Rotation) {
		return nil, false
	}
	return o.Rotation, true
}

// HasRotation returns a boolean if a field has been set.
func (o *Settings) HasRotation() bool {
	if o != nil && !IsNil(o.Rotation) {
		return true
	}

	return false
}

// SetRotation gets a reference to the given int32 and assigns it to the Rotation field.
func (o *Settings) SetRotation(v int32) {
	o.Rotation = &v
}

// GetOverheatMode returns the OverheatMode field value if set, zero value otherwise.
func (o *Settings) GetOverheatMode() int32 {
	if o == nil || IsNil(o.OverheatMode) {
		var ret int32
		return ret
	}
	return *o.OverheatMode
}

// GetOverheatModeOk returns a tuple with the OverheatMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOverheatModeOk() (*int32, bool) {
	if o == nil || IsNil(o.OverheatMode) {
		return nil, false
	}
	return o.OverheatMode, true
}

// HasOverheatMode returns a boolean if a field has been set.
func (o *Settings) HasOverheatMode() bool {
	if o != nil && !IsNil(o.OverheatMode) {
		return true
	}

	return false
}

// SetOverheatMode gets a reference to the given int32 and assigns it to the OverheatMode field.
func (o *Settings) SetOverheatMode(v int32) {
	o.OverheatMode = &v
}

// GetOverclockEnabled returns the OverclockEnabled field value if set, zero value otherwise.
func (o *Settings) GetOverclockEnabled() int32 {
	if o == nil || IsNil(o.OverclockEnabled) {
		var ret int32
		return ret
	}
	return *o.OverclockEnabled
}

// GetOverclockEnabledOk returns a tuple with the OverclockEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOverclockEnabledOk() (*int32, bool) {
	if o == nil || IsNil(o.OverclockEnabled) {
		return nil, false
	}
	return o.OverclockEnabled, true
}

// HasOverclockEnabled returns a boolean if a field has been set.
func (o *Settings) HasOverclockEnabled() bool {
	if o != nil && !IsNil(o.OverclockEnabled) {
		return true
	}

	return false
}

// SetOverclockEnabled gets a reference to the given int32 and assigns it to the OverclockEnabled field.
func (o *Settings) SetOverclockEnabled(v int32) {
	o.OverclockEnabled = &v
}

// GetInvertscreen returns the Invertscreen field value if set, zero value otherwise.
func (o *Settings) GetInvertscreen() int32 {
	if o == nil || IsNil(o.Invertscreen) {
		var ret int32
		return ret
	}
	return *o.Invertscreen
}

// GetInvertscreenOk returns a tuple with the Invertscreen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetInvertscreenOk() (*int32, bool) {
	if o == nil || IsNil(o.Invertscreen) {
		return nil, false
	}
	return o.Invertscreen, true
}

// HasInvertscreen returns a boolean if a field has been set.
func (o *Settings) HasInvertscreen() bool {
	if o != nil && !IsNil(o.Invertscreen) {
		return true
	}

	return false
}

// SetInvertscreen gets a reference to the given int32 and assigns it to the Invertscreen field.
func (o *Settings) SetInvertscreen(v int32) {
	o.Invertscreen = &v
}

// GetAutofanspeed returns the Autofanspeed field value if set, zero value otherwise.
func (o *Settings) GetAutofanspeed() int32 {
	if o == nil || IsNil(o.Autofanspeed) {
		var ret int32
		return ret
	}
	return *o.Autofanspeed
}

// GetAutofanspeedOk returns a tuple with the Autofanspeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetAutofanspeedOk() (*int32, bool) {
	if o == nil || IsNil(o.Autofanspeed) {
		return nil, false
	}
	return o.Autofanspeed, true
}

// HasAutofanspeed returns a boolean if a field has been set.
func (o *Settings) HasAutofanspeed() bool {
	if o != nil && !IsNil(o.Autofanspeed) {
		return true
	}

	return false
}

// SetAutofanspeed gets a reference to the given int32 and assigns it to the Autofanspeed field.
func (o *Settings) SetAutofanspeed(v int32) {
	o.Autofanspeed = &v
}

// GetFanspeed returns the Fanspeed field value if set, zero value otherwise.
func (o *Settings) GetFanspeed() int32 {
	if o == nil || IsNil(o.Fanspeed) {
		var ret int32
		return ret
	}
	return *o.Fanspeed
}

// GetFanspeedOk returns a tuple with the Fanspeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetFanspeedOk() (*int32, bool) {
	if o == nil || IsNil(o.Fanspeed) {
		return nil, false
	}
	return o.Fanspeed, true
}

// HasFanspeed returns a boolean if a field has been set.
func (o *Settings) HasFanspeed() bool {
	if o != nil && !IsNil(o.Fanspeed) {
		return true
	}

	return false
}

// SetFanspeed gets a reference to the given int32 and assigns it to the Fanspeed field.
func (o *Settings) SetFanspeed(v int32) {
	o.Fanspeed = &v
}

// GetTemptarget returns the Temptarget field value if set, zero value otherwise.
func (o *Settings) GetTemptarget() int32 {
	if o == nil || IsNil(o.Temptarget) {
		var ret int32
		return ret
	}
	return *o.Temptarget
}

// GetTemptargetOk returns a tuple with the Temptarget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetTemptargetOk() (*int32, bool) {
	if o == nil || IsNil(o.Temptarget) {
		return nil, false
	}
	return o.Temptarget, true
}

// HasTemptarget returns a boolean if a field has been set.
func (o *Settings) HasTemptarget() bool {
	if o != nil && !IsNil(o.Temptarget) {
		return true
	}

	return false
}

// SetTemptarget gets a reference to the given int32 and assigns it to the Temptarget field.
func (o *Settings) SetTemptarget(v int32) {
	o.Temptarget = &v
}

// GetDisplayTimeout returns the DisplayTimeout field value if set, zero value otherwise.
func (o *Settings) GetDisplayTimeout() int32 {
	if o == nil || IsNil(o.DisplayTimeout) {
		var ret int32
		return ret
	}
	return *o.DisplayTimeout
}

// GetDisplayTimeoutOk returns a tuple with the DisplayTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetDisplayTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.DisplayTimeout) {
		return nil, false
	}
	return o.DisplayTimeout, true
}

// HasDisplayTimeout returns a boolean if a field has been set.
func (o *Settings) HasDisplayTimeout() bool {
	if o != nil && !IsNil(o.DisplayTimeout) {
		return true
	}

	return false
}

// SetDisplayTimeout gets a reference to the given int32 and assigns it to the DisplayTimeout field.
func (o *Settings) SetDisplayTimeout(v int32) {
	o.DisplayTimeout = &v
}

// GetStatsFrequency returns the StatsFrequency field value if set, zero value otherwise.
func (o *Settings) GetStatsFrequency() int32 {
	if o == nil || IsNil(o.StatsFrequency) {
		var ret int32
		return ret
	}
	return *o.StatsFrequency
}

// GetStatsFrequencyOk returns a tuple with the StatsFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetStatsFrequencyOk() (*int32, bool) {
	if o == nil || IsNil(o.StatsFrequency) {
		return nil, false
	}
	return o.StatsFrequency, true
}

// HasStatsFrequency returns a boolean if a field has been set.
func (o *Settings) HasStatsFrequency() bool {
	if o != nil && !IsNil(o.StatsFrequency) {
		return true
	}

	return false
}

// SetStatsFrequency gets a reference to the given int32 and assigns it to the StatsFrequency field.
func (o *Settings) SetStatsFrequency(v int32) {
	o.StatsFrequency = &v
}

func (o Settings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Settings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UseFallbackStratum) {
		toSerialize["useFallbackStratum"] = o.UseFallbackStratum
	}
	if !IsNil(o.StratumURL) {
		toSerialize["stratumURL"] = o.StratumURL
	}
	if !IsNil(o.FallbackStratumURL) {
		toSerialize["fallbackStratumURL"] = o.FallbackStratumURL
	}
	if !IsNil(o.StratumUser) {
		toSerialize["stratumUser"] = o.StratumUser
	}
	if !IsNil(o.StratumPassword) {
		toSerialize["stratumPassword"] = o.StratumPassword
	}
	if !IsNil(o.FallbackStratumUser) {
		toSerialize["fallbackStratumUser"] = o.FallbackStratumUser
	}
	if !IsNil(o.FallbackStratumPassword) {
		toSerialize["fallbackStratumPassword"] = o.FallbackStratumPassword
	}
	if !IsNil(o.StratumPort) {
		toSerialize["stratumPort"] = o.StratumPort
	}
	if !IsNil(o.FallbackStratumPort) {
		toSerialize["fallbackStratumPort"] = o.FallbackStratumPort
	}
	if !IsNil(o.Ssid) {
		toSerialize["ssid"] = o.Ssid
	}
	if !IsNil(o.WifiPass) {
		toSerialize["wifiPass"] = o.WifiPass
	}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !IsNil(o.CoreVoltage) {
		toSerialize["coreVoltage"] = o.CoreVoltage
	}
	if !IsNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if !IsNil(o.Rotation) {
		toSerialize["rotation"] = o.Rotation
	}
	if !IsNil(o.OverheatMode) {
		toSerialize["overheat_mode"] = o.OverheatMode
	}
	if !IsNil(o.OverclockEnabled) {
		toSerialize["overclockEnabled"] = o.OverclockEnabled
	}
	if !IsNil(o.Invertscreen) {
		toSerialize["invertscreen"] = o.Invertscreen
	}
	if !IsNil(o.Autofanspeed) {
		toSerialize["autofanspeed"] = o.Autofanspeed
	}
	if !IsNil(o.Fanspeed) {
		toSerialize["fanspeed"] = o.Fanspeed
	}
	if !IsNil(o.Temptarget) {
		toSerialize["temptarget"] = o.Temptarget
	}
	if !IsNil(o.DisplayTimeout) {
		toSerialize["displayTimeout"] = o.DisplayTimeout
	}
	if !IsNil(o.StatsFrequency) {
		toSerialize["statsFrequency"] = o.StatsFrequency
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Settings) UnmarshalJSON(data []byte) (err error) {
	varSettings := _Settings{}

	err = json.Unmarshal(data, &varSettings)

	if err != nil {
		return err
	}

	*o = Settings(varSettings)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "useFallbackStratum")
		delete(additionalProperties, "stratumURL")
		delete(additionalProperties, "fallbackStratumURL")
		delete(additionalProperties, "stratumUser")
		delete(additionalProperties, "stratumPassword")
		delete(additionalProperties, "fallbackStratumUser")
		delete(additionalProperties, "fallbackStratumPassword")
		delete(additionalProperties, "stratumPort")
		delete(additionalProperties, "fallbackStratumPort")
		delete(additionalProperties, "ssid")
		delete(additionalProperties, "wifiPass")
		delete(additionalProperties, "hostname")
		delete(additionalProperties, "coreVoltage")
		delete(additionalProperties, "frequency")
		delete(additionalProperties, "rotation")
		delete(additionalProperties, "overheat_mode")
		delete(additionalProperties, "overclockEnabled")
		delete(additionalProperties, "invertscreen")
		delete(additionalProperties, "autofanspeed")
		delete(additionalProperties, "fanspeed")
		delete(additionalProperties, "temptarget")
		delete(additionalProperties, "displayTimeout")
		delete(additionalProperties, "statsFrequency")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSettings struct {
	value *Settings
	isSet bool
}

func (v NullableSettings) Get() *Settings {
	return v.value
}

func (v *NullableSettings) Set(val *Settings) {
	v.value = val
	v.isSet = true
}

func (v NullableSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettings(val *Settings) *NullableSettings {
	return &NullableSettings{value: val, isSet: true}
}

func (v NullableSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


