/*
ESP-Miner API

API specification for ESP-Miner HTTP server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScanWifiNetworks200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScanWifiNetworks200Response{}

// ScanWifiNetworks200Response struct for ScanWifiNetworks200Response
type ScanWifiNetworks200Response struct {
	Networks []WifiNetwork `json:"networks"`
}

type _ScanWifiNetworks200Response ScanWifiNetworks200Response

// NewScanWifiNetworks200Response instantiates a new ScanWifiNetworks200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScanWifiNetworks200Response(networks []WifiNetwork) *ScanWifiNetworks200Response {
	this := ScanWifiNetworks200Response{}
	this.Networks = networks
	return &this
}

// NewScanWifiNetworks200ResponseWithDefaults instantiates a new ScanWifiNetworks200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScanWifiNetworks200ResponseWithDefaults() *ScanWifiNetworks200Response {
	this := ScanWifiNetworks200Response{}
	return &this
}

// GetNetworks returns the Networks field value
func (o *ScanWifiNetworks200Response) GetNetworks() []WifiNetwork {
	if o == nil {
		var ret []WifiNetwork
		return ret
	}

	return o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value
// and a boolean to check if the value has been set.
func (o *ScanWifiNetworks200Response) GetNetworksOk() ([]WifiNetwork, bool) {
	if o == nil {
		return nil, false
	}
	return o.Networks, true
}

// SetNetworks sets field value
func (o *ScanWifiNetworks200Response) SetNetworks(v []WifiNetwork) {
	o.Networks = v
}

func (o ScanWifiNetworks200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScanWifiNetworks200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["networks"] = o.Networks
	return toSerialize, nil
}

func (o *ScanWifiNetworks200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"networks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScanWifiNetworks200Response := _ScanWifiNetworks200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScanWifiNetworks200Response)

	if err != nil {
		return err
	}

	*o = ScanWifiNetworks200Response(varScanWifiNetworks200Response)

	return err
}

type NullableScanWifiNetworks200Response struct {
	value *ScanWifiNetworks200Response
	isSet bool
}

func (v NullableScanWifiNetworks200Response) Get() *ScanWifiNetworks200Response {
	return v.value
}

func (v *NullableScanWifiNetworks200Response) Set(val *ScanWifiNetworks200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableScanWifiNetworks200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableScanWifiNetworks200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScanWifiNetworks200Response(val *ScanWifiNetworks200Response) *NullableScanWifiNetworks200Response {
	return &NullableScanWifiNetworks200Response{value: val, isSet: true}
}

func (v NullableScanWifiNetworks200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScanWifiNetworks200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


