/*
ESP-Miner API

API specification for ESP-Miner HTTP server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemStatistics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemStatistics{}

// SystemStatistics struct for SystemStatistics
type SystemStatistics struct {
	// Current timestamp as a reference
	CurrentTimestamp float32 `json:"currentTimestamp"`
	// Labels for statistics data value index
	Labels []string `json:"labels"`
	// Statistics data point(s)
	Statistics [][]float32 `json:"statistics"`
}

type _SystemStatistics SystemStatistics

// NewSystemStatistics instantiates a new SystemStatistics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemStatistics(currentTimestamp float32, labels []string, statistics [][]float32) *SystemStatistics {
	this := SystemStatistics{}
	this.CurrentTimestamp = currentTimestamp
	this.Labels = labels
	this.Statistics = statistics
	return &this
}

// NewSystemStatisticsWithDefaults instantiates a new SystemStatistics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemStatisticsWithDefaults() *SystemStatistics {
	this := SystemStatistics{}
	return &this
}

// GetCurrentTimestamp returns the CurrentTimestamp field value
func (o *SystemStatistics) GetCurrentTimestamp() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentTimestamp
}

// GetCurrentTimestampOk returns a tuple with the CurrentTimestamp field value
// and a boolean to check if the value has been set.
func (o *SystemStatistics) GetCurrentTimestampOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentTimestamp, true
}

// SetCurrentTimestamp sets field value
func (o *SystemStatistics) SetCurrentTimestamp(v float32) {
	o.CurrentTimestamp = v
}

// GetLabels returns the Labels field value
func (o *SystemStatistics) GetLabels() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *SystemStatistics) GetLabelsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Labels, true
}

// SetLabels sets field value
func (o *SystemStatistics) SetLabels(v []string) {
	o.Labels = v
}

// GetStatistics returns the Statistics field value
func (o *SystemStatistics) GetStatistics() [][]float32 {
	if o == nil {
		var ret [][]float32
		return ret
	}

	return o.Statistics
}

// GetStatisticsOk returns a tuple with the Statistics field value
// and a boolean to check if the value has been set.
func (o *SystemStatistics) GetStatisticsOk() ([][]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Statistics, true
}

// SetStatistics sets field value
func (o *SystemStatistics) SetStatistics(v [][]float32) {
	o.Statistics = v
}

func (o SystemStatistics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemStatistics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currentTimestamp"] = o.CurrentTimestamp
	toSerialize["labels"] = o.Labels
	toSerialize["statistics"] = o.Statistics
	return toSerialize, nil
}

func (o *SystemStatistics) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currentTimestamp",
		"labels",
		"statistics",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemStatistics := _SystemStatistics{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemStatistics)

	if err != nil {
		return err
	}

	*o = SystemStatistics(varSystemStatistics)

	return err
}

type NullableSystemStatistics struct {
	value *SystemStatistics
	isSet bool
}

func (v NullableSystemStatistics) Get() *SystemStatistics {
	return v.value
}

func (v *NullableSystemStatistics) Set(val *SystemStatistics) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemStatistics) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemStatistics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemStatistics(val *SystemStatistics) *NullableSystemStatistics {
	return &NullableSystemStatistics{value: val, isSet: true}
}

func (v NullableSystemStatistics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemStatistics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


