/*
ESP-Miner API

API specification for ESP-Miner HTTP server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemInfo{}

// SystemInfo struct for SystemInfo
type SystemInfo struct {
	// ASIC model identifier
	ASICModel string `json:"ASICModel"`
	// Whether AP mode is enabled (0=no, 1=yes)
	ApEnabled float32 `json:"apEnabled"`
	// Automatic fan speed control (0=manual, 1=auto)
	Autofanspeed float32 `json:"autofanspeed"`
	// Best difficulty achieved
	BestDiff float32 `json:"bestDiff"`
	// Best difficulty achieved in current session
	BestSessionDiff float32 `json:"bestSessionDiff"`
	// Hardware board version
	BoardVersion string `json:"boardVersion"`
	// Configured ASIC core voltage
	CoreVoltage float32 `json:"coreVoltage"`
	// Actual measured ASIC core voltage
	CoreVoltageActual float32 `json:"coreVoltageActual"`
	// Current draw in milliamps
	Current float32 `json:"current"`
	// The configured display
	Display string `json:"display"`
	// Enable fallback pool extranonce subscription
	FallbackStratumExtranonceSubscribe bool `json:"fallbackStratumExtranonceSubscribe"`
	// Fallback stratum server port
	FallbackStratumPort float32 `json:"fallbackStratumPort"`
	// Fallback pool suggested difficulty
	FallbackStratumSuggestedDifficulty float32 `json:"fallbackStratumSuggestedDifficulty"`
	// Fallback stratum server URL
	FallbackStratumURL string `json:"fallbackStratumURL"`
	// Fallback stratum username
	FallbackStratumUser string `json:"fallbackStratumUser"`
	// Enable fallback stratum TLS
	FallbackStratumTLS bool `json:"fallbackStratumTLS"`
	// Fallback stratum TLS cert
	FallbackStratumCert string `json:"fallbackStratumCert"`
	// Current fan speed in RPM
	Fanrpm float32 `json:"fanrpm"`
	// Current secondary fan speed in RPM
	Fan2rpm float32 `json:"fan2rpm"`
	// Current fan speed percentage
	Fanspeed float32 `json:"fanspeed"`
	// Target Temperature for the PID Controller
	Temptarget float32 `json:"temptarget"`
	// Pool response time in ms
	ResponseTime float32 `json:"responseTime"`
	// Screen rotation setting (0, 90, 180, 270)
	Rotation float32 `json:"rotation"`
	// Available heap memory in bytes
	FreeHeap float32 `json:"freeHeap"`
	// Available internal heap memory in bytes
	FreeHeapInternal float32 `json:"freeHeapInternal"`
	// Available Spiram heap memory in bytes
	FreeHeapSpiram float32 `json:"freeHeapSpiram"`
	// ASIC frequency in MHz
	Frequency float32 `json:"frequency"`
	// Current hashrate in Gh/s
	HashRate float32 `json:"hashRate"`
	// Current hashrate 1m average
	HashRate1m float32 `json:"hashRate_1m"`
	// Current hashrate 10m average
	HashRate10m float32 `json:"hashRate_10m"`
	// Current hashrate 1h average
	HashRate1h float32 `json:"hashRate_1h"`
	// Expected hashrate at current voltage/frequency settings, in Gh/s
	ExpectedHashrate float32 `json:"expectedHashrate"`
	// Hash error percentage
	ErrorPercentage float32 `json:"errorPercentage"`
	// Device hostname
	Hostname string `json:"hostname"`
	// ESP-IDF version
	IdfVersion string `json:"idfVersion"`
	// Screen invert setting (0=normal, 1=inverted)
	Invertscreen float32 `json:"invertscreen"`
	// Whether PSRAM is available (0=no, 1=yes)
	IsPSRAMAvailable float32 `json:"isPSRAMAvailable"`
	// Whether using fallback stratum (0=no, 1=yes)
	IsUsingFallbackStratum float32 `json:"isUsingFallbackStratum"`
	// Device MAC address
	MacAddr string `json:"macAddr"`
	// Fan speed when auto fan speed is disabled
	ManualFanSpeed int32 `json:"manualFanSpeed"`
	// Maxmium power draw of the board in watts
	MaxPower int32 `json:"maxPower"`
	// Minimum fan speed percentage when using auto fan control
	MinFanSpeed int32 `json:"minFanSpeed"`
	// Nominal board voltage
	NominalVoltage int32 `json:"nominalVoltage"`
	// Overheat protection mode
	OverheatMode float32 `json:"overheat_mode"`
	// Set custom voltage/frequency in AxeOS
	OverclockEnabled int32 `json:"overclockEnabled"`
	// Current pool address family
	PoolConnectionInfo string `json:"poolConnectionInfo"`
	// Current pool difficulty
	PoolDifficulty float32 `json:"poolDifficulty"`
	// Power consumption in watts
	Power float32 `json:"power"`
	// Voltage regulator fault reason, if any
	PowerFault *string `json:"power_fault,omitempty"`
	// Reason for the last system reset
	ResetReason string `json:"resetReason"`
	// Currently active OTA partition
	RunningPartition string `json:"runningPartition"`
	// Number of accepted shares
	SharesAccepted float32 `json:"sharesAccepted"`
	// Number of rejected shares
	SharesRejected float32 `json:"sharesRejected"`
	// Reason(s) shares were rejected
	SharesRejectedReasons []SharesRejectedReason `json:"sharesRejectedReasons"`
	// Number of small cores
	SmallCoreCount float32 `json:"smallCoreCount"`
	// Connected WiFi network SSID
	Ssid string `json:"ssid"`
	// IPv4 address
	Ipv4 string `json:"ipv4"`
	// IPv6 address
	Ipv6 string `json:"ipv6"`
	// Enable pool extranonce subscription
	StratumExtranonceSubscribe bool `json:"stratumExtranonceSubscribe"`
	// Primary stratum server port
	StratumPort float32 `json:"stratumPort"`
	// Pool suggested difficulty
	StratumSuggestedDifficulty float32 `json:"stratumSuggestedDifficulty"`
	// Primary stratum server URL
	StratumURL string `json:"stratumURL"`
	// Primary stratum username
	StratumUser string `json:"stratumUser"`
	// Enable primary pool TLS
	StratumTLS bool `json:"stratumTLS"`
	// Primary stratum TLS cert
	StratumCert string `json:"stratumCert"`
	// Average chip temperature
	Temp float32 `json:"temp"`
	// Average chip temperature from second sensor
	Temp2 float32 `json:"temp2"`
	// System uptime in seconds
	UptimeSeconds float32 `json:"uptimeSeconds"`
	// Firmware version
	Version string `json:"version"`
	// AxeOS version
	AxeOSVersion string `json:"axeOSVersion"`
	// Input voltage
	Voltage float32 `json:"voltage"`
	// Voltage regulator temperature
	VrTemp float32 `json:"vrTemp"`
	// WiFi connection status
	WifiStatus string `json:"wifiStatus"`
	// WiFi signal strength
	WifiRSSI float32 `json:"wifiRSSI"`
	// Turn off display after timeout
	DisplayTimeout float32 `json:"displayTimeout"`
	// Statistics frequency in seconds
	StatsFrequency float32 `json:"statsFrequency"`
	// Current block height
	BlockHeight int32 `json:"blockHeight"`
	// Scriptsig extracted from coinbase transaction
	Scriptsig string `json:"scriptsig"`
	// Current network difficulty
	NetworkDifficulty float32 `json:"networkDifficulty"`
	// Whether a block was found (0=no, 1=yes)
	BlockFound float32 `json:"blockFound"`
	HashrateMonitor SystemInfoHashrateMonitor `json:"hashrateMonitor"`
}

type _SystemInfo SystemInfo

// NewSystemInfo instantiates a new SystemInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemInfo(aSICModel string, apEnabled float32, autofanspeed float32, bestDiff float32, bestSessionDiff float32, boardVersion string, coreVoltage float32, coreVoltageActual float32, current float32, display string, fallbackStratumExtranonceSubscribe bool, fallbackStratumPort float32, fallbackStratumSuggestedDifficulty float32, fallbackStratumURL string, fallbackStratumUser string, fallbackStratumTLS bool, fallbackStratumCert string, fanrpm float32, fan2rpm float32, fanspeed float32, temptarget float32, responseTime float32, rotation float32, freeHeap float32, freeHeapInternal float32, freeHeapSpiram float32, frequency float32, hashRate float32, hashRate1m float32, hashRate10m float32, hashRate1h float32, expectedHashrate float32, errorPercentage float32, hostname string, idfVersion string, invertscreen float32, isPSRAMAvailable float32, isUsingFallbackStratum float32, macAddr string, manualFanSpeed int32, maxPower int32, minFanSpeed int32, nominalVoltage int32, overheatMode float32, overclockEnabled int32, poolConnectionInfo string, poolDifficulty float32, power float32, resetReason string, runningPartition string, sharesAccepted float32, sharesRejected float32, sharesRejectedReasons []SharesRejectedReason, smallCoreCount float32, ssid string, ipv4 string, ipv6 string, stratumExtranonceSubscribe bool, stratumPort float32, stratumSuggestedDifficulty float32, stratumURL string, stratumUser string, stratumTLS bool, stratumCert string, temp float32, temp2 float32, uptimeSeconds float32, version string, axeOSVersion string, voltage float32, vrTemp float32, wifiStatus string, wifiRSSI float32, displayTimeout float32, statsFrequency float32, blockHeight int32, scriptsig string, networkDifficulty float32, blockFound float32, hashrateMonitor SystemInfoHashrateMonitor) *SystemInfo {
	this := SystemInfo{}
	this.ASICModel = aSICModel
	this.ApEnabled = apEnabled
	this.Autofanspeed = autofanspeed
	this.BestDiff = bestDiff
	this.BestSessionDiff = bestSessionDiff
	this.BoardVersion = boardVersion
	this.CoreVoltage = coreVoltage
	this.CoreVoltageActual = coreVoltageActual
	this.Current = current
	this.Display = display
	this.FallbackStratumExtranonceSubscribe = fallbackStratumExtranonceSubscribe
	this.FallbackStratumPort = fallbackStratumPort
	this.FallbackStratumSuggestedDifficulty = fallbackStratumSuggestedDifficulty
	this.FallbackStratumURL = fallbackStratumURL
	this.FallbackStratumUser = fallbackStratumUser
	this.FallbackStratumTLS = fallbackStratumTLS
	this.FallbackStratumCert = fallbackStratumCert
	this.Fanrpm = fanrpm
	this.Fan2rpm = fan2rpm
	this.Fanspeed = fanspeed
	this.Temptarget = temptarget
	this.ResponseTime = responseTime
	this.Rotation = rotation
	this.FreeHeap = freeHeap
	this.FreeHeapInternal = freeHeapInternal
	this.FreeHeapSpiram = freeHeapSpiram
	this.Frequency = frequency
	this.HashRate = hashRate
	this.HashRate1m = hashRate1m
	this.HashRate10m = hashRate10m
	this.HashRate1h = hashRate1h
	this.ExpectedHashrate = expectedHashrate
	this.ErrorPercentage = errorPercentage
	this.Hostname = hostname
	this.IdfVersion = idfVersion
	this.Invertscreen = invertscreen
	this.IsPSRAMAvailable = isPSRAMAvailable
	this.IsUsingFallbackStratum = isUsingFallbackStratum
	this.MacAddr = macAddr
	this.ManualFanSpeed = manualFanSpeed
	this.MaxPower = maxPower
	this.MinFanSpeed = minFanSpeed
	this.NominalVoltage = nominalVoltage
	this.OverheatMode = overheatMode
	this.OverclockEnabled = overclockEnabled
	this.PoolConnectionInfo = poolConnectionInfo
	this.PoolDifficulty = poolDifficulty
	this.Power = power
	this.ResetReason = resetReason
	this.RunningPartition = runningPartition
	this.SharesAccepted = sharesAccepted
	this.SharesRejected = sharesRejected
	this.SharesRejectedReasons = sharesRejectedReasons
	this.SmallCoreCount = smallCoreCount
	this.Ssid = ssid
	this.Ipv4 = ipv4
	this.Ipv6 = ipv6
	this.StratumExtranonceSubscribe = stratumExtranonceSubscribe
	this.StratumPort = stratumPort
	this.StratumSuggestedDifficulty = stratumSuggestedDifficulty
	this.StratumURL = stratumURL
	this.StratumUser = stratumUser
	this.StratumTLS = stratumTLS
	this.StratumCert = stratumCert
	this.Temp = temp
	this.Temp2 = temp2
	this.UptimeSeconds = uptimeSeconds
	this.Version = version
	this.AxeOSVersion = axeOSVersion
	this.Voltage = voltage
	this.VrTemp = vrTemp
	this.WifiStatus = wifiStatus
	this.WifiRSSI = wifiRSSI
	this.DisplayTimeout = displayTimeout
	this.StatsFrequency = statsFrequency
	this.BlockHeight = blockHeight
	this.Scriptsig = scriptsig
	this.NetworkDifficulty = networkDifficulty
	this.BlockFound = blockFound
	this.HashrateMonitor = hashrateMonitor
	return &this
}

// NewSystemInfoWithDefaults instantiates a new SystemInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemInfoWithDefaults() *SystemInfo {
	this := SystemInfo{}
	return &this
}

// GetASICModel returns the ASICModel field value
func (o *SystemInfo) GetASICModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ASICModel
}

// GetASICModelOk returns a tuple with the ASICModel field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetASICModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ASICModel, true
}

// SetASICModel sets field value
func (o *SystemInfo) SetASICModel(v string) {
	o.ASICModel = v
}

// GetApEnabled returns the ApEnabled field value
func (o *SystemInfo) GetApEnabled() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ApEnabled
}

// GetApEnabledOk returns a tuple with the ApEnabled field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetApEnabledOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApEnabled, true
}

// SetApEnabled sets field value
func (o *SystemInfo) SetApEnabled(v float32) {
	o.ApEnabled = v
}

// GetAutofanspeed returns the Autofanspeed field value
func (o *SystemInfo) GetAutofanspeed() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Autofanspeed
}

// GetAutofanspeedOk returns a tuple with the Autofanspeed field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetAutofanspeedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Autofanspeed, true
}

// SetAutofanspeed sets field value
func (o *SystemInfo) SetAutofanspeed(v float32) {
	o.Autofanspeed = v
}

// GetBestDiff returns the BestDiff field value
func (o *SystemInfo) GetBestDiff() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BestDiff
}

// GetBestDiffOk returns a tuple with the BestDiff field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetBestDiffOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BestDiff, true
}

// SetBestDiff sets field value
func (o *SystemInfo) SetBestDiff(v float32) {
	o.BestDiff = v
}

// GetBestSessionDiff returns the BestSessionDiff field value
func (o *SystemInfo) GetBestSessionDiff() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BestSessionDiff
}

// GetBestSessionDiffOk returns a tuple with the BestSessionDiff field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetBestSessionDiffOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BestSessionDiff, true
}

// SetBestSessionDiff sets field value
func (o *SystemInfo) SetBestSessionDiff(v float32) {
	o.BestSessionDiff = v
}

// GetBoardVersion returns the BoardVersion field value
func (o *SystemInfo) GetBoardVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BoardVersion
}

// GetBoardVersionOk returns a tuple with the BoardVersion field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetBoardVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BoardVersion, true
}

// SetBoardVersion sets field value
func (o *SystemInfo) SetBoardVersion(v string) {
	o.BoardVersion = v
}

// GetCoreVoltage returns the CoreVoltage field value
func (o *SystemInfo) GetCoreVoltage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CoreVoltage
}

// GetCoreVoltageOk returns a tuple with the CoreVoltage field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetCoreVoltageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CoreVoltage, true
}

// SetCoreVoltage sets field value
func (o *SystemInfo) SetCoreVoltage(v float32) {
	o.CoreVoltage = v
}

// GetCoreVoltageActual returns the CoreVoltageActual field value
func (o *SystemInfo) GetCoreVoltageActual() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CoreVoltageActual
}

// GetCoreVoltageActualOk returns a tuple with the CoreVoltageActual field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetCoreVoltageActualOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CoreVoltageActual, true
}

// SetCoreVoltageActual sets field value
func (o *SystemInfo) SetCoreVoltageActual(v float32) {
	o.CoreVoltageActual = v
}

// GetCurrent returns the Current field value
func (o *SystemInfo) GetCurrent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetCurrentOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *SystemInfo) SetCurrent(v float32) {
	o.Current = v
}

// GetDisplay returns the Display field value
func (o *SystemInfo) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *SystemInfo) SetDisplay(v string) {
	o.Display = v
}

// GetFallbackStratumExtranonceSubscribe returns the FallbackStratumExtranonceSubscribe field value
func (o *SystemInfo) GetFallbackStratumExtranonceSubscribe() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FallbackStratumExtranonceSubscribe
}

// GetFallbackStratumExtranonceSubscribeOk returns a tuple with the FallbackStratumExtranonceSubscribe field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFallbackStratumExtranonceSubscribeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FallbackStratumExtranonceSubscribe, true
}

// SetFallbackStratumExtranonceSubscribe sets field value
func (o *SystemInfo) SetFallbackStratumExtranonceSubscribe(v bool) {
	o.FallbackStratumExtranonceSubscribe = v
}

// GetFallbackStratumPort returns the FallbackStratumPort field value
func (o *SystemInfo) GetFallbackStratumPort() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FallbackStratumPort
}

// GetFallbackStratumPortOk returns a tuple with the FallbackStratumPort field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFallbackStratumPortOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FallbackStratumPort, true
}

// SetFallbackStratumPort sets field value
func (o *SystemInfo) SetFallbackStratumPort(v float32) {
	o.FallbackStratumPort = v
}

// GetFallbackStratumSuggestedDifficulty returns the FallbackStratumSuggestedDifficulty field value
func (o *SystemInfo) GetFallbackStratumSuggestedDifficulty() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FallbackStratumSuggestedDifficulty
}

// GetFallbackStratumSuggestedDifficultyOk returns a tuple with the FallbackStratumSuggestedDifficulty field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFallbackStratumSuggestedDifficultyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FallbackStratumSuggestedDifficulty, true
}

// SetFallbackStratumSuggestedDifficulty sets field value
func (o *SystemInfo) SetFallbackStratumSuggestedDifficulty(v float32) {
	o.FallbackStratumSuggestedDifficulty = v
}

// GetFallbackStratumURL returns the FallbackStratumURL field value
func (o *SystemInfo) GetFallbackStratumURL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FallbackStratumURL
}

// GetFallbackStratumURLOk returns a tuple with the FallbackStratumURL field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFallbackStratumURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FallbackStratumURL, true
}

// SetFallbackStratumURL sets field value
func (o *SystemInfo) SetFallbackStratumURL(v string) {
	o.FallbackStratumURL = v
}

// GetFallbackStratumUser returns the FallbackStratumUser field value
func (o *SystemInfo) GetFallbackStratumUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FallbackStratumUser
}

// GetFallbackStratumUserOk returns a tuple with the FallbackStratumUser field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFallbackStratumUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FallbackStratumUser, true
}

// SetFallbackStratumUser sets field value
func (o *SystemInfo) SetFallbackStratumUser(v string) {
	o.FallbackStratumUser = v
}

// GetFallbackStratumTLS returns the FallbackStratumTLS field value
func (o *SystemInfo) GetFallbackStratumTLS() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FallbackStratumTLS
}

// GetFallbackStratumTLSOk returns a tuple with the FallbackStratumTLS field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFallbackStratumTLSOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FallbackStratumTLS, true
}

// SetFallbackStratumTLS sets field value
func (o *SystemInfo) SetFallbackStratumTLS(v bool) {
	o.FallbackStratumTLS = v
}

// GetFallbackStratumCert returns the FallbackStratumCert field value
func (o *SystemInfo) GetFallbackStratumCert() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FallbackStratumCert
}

// GetFallbackStratumCertOk returns a tuple with the FallbackStratumCert field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFallbackStratumCertOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FallbackStratumCert, true
}

// SetFallbackStratumCert sets field value
func (o *SystemInfo) SetFallbackStratumCert(v string) {
	o.FallbackStratumCert = v
}

// GetFanrpm returns the Fanrpm field value
func (o *SystemInfo) GetFanrpm() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Fanrpm
}

// GetFanrpmOk returns a tuple with the Fanrpm field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFanrpmOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fanrpm, true
}

// SetFanrpm sets field value
func (o *SystemInfo) SetFanrpm(v float32) {
	o.Fanrpm = v
}

// GetFan2rpm returns the Fan2rpm field value
func (o *SystemInfo) GetFan2rpm() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Fan2rpm
}

// GetFan2rpmOk returns a tuple with the Fan2rpm field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFan2rpmOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fan2rpm, true
}

// SetFan2rpm sets field value
func (o *SystemInfo) SetFan2rpm(v float32) {
	o.Fan2rpm = v
}

// GetFanspeed returns the Fanspeed field value
func (o *SystemInfo) GetFanspeed() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Fanspeed
}

// GetFanspeedOk returns a tuple with the Fanspeed field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFanspeedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fanspeed, true
}

// SetFanspeed sets field value
func (o *SystemInfo) SetFanspeed(v float32) {
	o.Fanspeed = v
}

// GetTemptarget returns the Temptarget field value
func (o *SystemInfo) GetTemptarget() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Temptarget
}

// GetTemptargetOk returns a tuple with the Temptarget field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetTemptargetOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Temptarget, true
}

// SetTemptarget sets field value
func (o *SystemInfo) SetTemptarget(v float32) {
	o.Temptarget = v
}

// GetResponseTime returns the ResponseTime field value
func (o *SystemInfo) GetResponseTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ResponseTime
}

// GetResponseTimeOk returns a tuple with the ResponseTime field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetResponseTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseTime, true
}

// SetResponseTime sets field value
func (o *SystemInfo) SetResponseTime(v float32) {
	o.ResponseTime = v
}

// GetRotation returns the Rotation field value
func (o *SystemInfo) GetRotation() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rotation
}

// GetRotationOk returns a tuple with the Rotation field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetRotationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rotation, true
}

// SetRotation sets field value
func (o *SystemInfo) SetRotation(v float32) {
	o.Rotation = v
}

// GetFreeHeap returns the FreeHeap field value
func (o *SystemInfo) GetFreeHeap() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FreeHeap
}

// GetFreeHeapOk returns a tuple with the FreeHeap field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFreeHeapOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreeHeap, true
}

// SetFreeHeap sets field value
func (o *SystemInfo) SetFreeHeap(v float32) {
	o.FreeHeap = v
}

// GetFreeHeapInternal returns the FreeHeapInternal field value
func (o *SystemInfo) GetFreeHeapInternal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FreeHeapInternal
}

// GetFreeHeapInternalOk returns a tuple with the FreeHeapInternal field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFreeHeapInternalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreeHeapInternal, true
}

// SetFreeHeapInternal sets field value
func (o *SystemInfo) SetFreeHeapInternal(v float32) {
	o.FreeHeapInternal = v
}

// GetFreeHeapSpiram returns the FreeHeapSpiram field value
func (o *SystemInfo) GetFreeHeapSpiram() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FreeHeapSpiram
}

// GetFreeHeapSpiramOk returns a tuple with the FreeHeapSpiram field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFreeHeapSpiramOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreeHeapSpiram, true
}

// SetFreeHeapSpiram sets field value
func (o *SystemInfo) SetFreeHeapSpiram(v float32) {
	o.FreeHeapSpiram = v
}

// GetFrequency returns the Frequency field value
func (o *SystemInfo) GetFrequency() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetFrequencyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frequency, true
}

// SetFrequency sets field value
func (o *SystemInfo) SetFrequency(v float32) {
	o.Frequency = v
}

// GetHashRate returns the HashRate field value
func (o *SystemInfo) GetHashRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.HashRate
}

// GetHashRateOk returns a tuple with the HashRate field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetHashRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HashRate, true
}

// SetHashRate sets field value
func (o *SystemInfo) SetHashRate(v float32) {
	o.HashRate = v
}

// GetHashRate1m returns the HashRate1m field value
func (o *SystemInfo) GetHashRate1m() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.HashRate1m
}

// GetHashRate1mOk returns a tuple with the HashRate1m field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetHashRate1mOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HashRate1m, true
}

// SetHashRate1m sets field value
func (o *SystemInfo) SetHashRate1m(v float32) {
	o.HashRate1m = v
}

// GetHashRate10m returns the HashRate10m field value
func (o *SystemInfo) GetHashRate10m() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.HashRate10m
}

// GetHashRate10mOk returns a tuple with the HashRate10m field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetHashRate10mOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HashRate10m, true
}

// SetHashRate10m sets field value
func (o *SystemInfo) SetHashRate10m(v float32) {
	o.HashRate10m = v
}

// GetHashRate1h returns the HashRate1h field value
func (o *SystemInfo) GetHashRate1h() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.HashRate1h
}

// GetHashRate1hOk returns a tuple with the HashRate1h field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetHashRate1hOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HashRate1h, true
}

// SetHashRate1h sets field value
func (o *SystemInfo) SetHashRate1h(v float32) {
	o.HashRate1h = v
}

// GetExpectedHashrate returns the ExpectedHashrate field value
func (o *SystemInfo) GetExpectedHashrate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ExpectedHashrate
}

// GetExpectedHashrateOk returns a tuple with the ExpectedHashrate field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetExpectedHashrateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedHashrate, true
}

// SetExpectedHashrate sets field value
func (o *SystemInfo) SetExpectedHashrate(v float32) {
	o.ExpectedHashrate = v
}

// GetErrorPercentage returns the ErrorPercentage field value
func (o *SystemInfo) GetErrorPercentage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ErrorPercentage
}

// GetErrorPercentageOk returns a tuple with the ErrorPercentage field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetErrorPercentageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorPercentage, true
}

// SetErrorPercentage sets field value
func (o *SystemInfo) SetErrorPercentage(v float32) {
	o.ErrorPercentage = v
}

// GetHostname returns the Hostname field value
func (o *SystemInfo) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *SystemInfo) SetHostname(v string) {
	o.Hostname = v
}

// GetIdfVersion returns the IdfVersion field value
func (o *SystemInfo) GetIdfVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdfVersion
}

// GetIdfVersionOk returns a tuple with the IdfVersion field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetIdfVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdfVersion, true
}

// SetIdfVersion sets field value
func (o *SystemInfo) SetIdfVersion(v string) {
	o.IdfVersion = v
}

// GetInvertscreen returns the Invertscreen field value
func (o *SystemInfo) GetInvertscreen() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Invertscreen
}

// GetInvertscreenOk returns a tuple with the Invertscreen field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetInvertscreenOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Invertscreen, true
}

// SetInvertscreen sets field value
func (o *SystemInfo) SetInvertscreen(v float32) {
	o.Invertscreen = v
}

// GetIsPSRAMAvailable returns the IsPSRAMAvailable field value
func (o *SystemInfo) GetIsPSRAMAvailable() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.IsPSRAMAvailable
}

// GetIsPSRAMAvailableOk returns a tuple with the IsPSRAMAvailable field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetIsPSRAMAvailableOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPSRAMAvailable, true
}

// SetIsPSRAMAvailable sets field value
func (o *SystemInfo) SetIsPSRAMAvailable(v float32) {
	o.IsPSRAMAvailable = v
}

// GetIsUsingFallbackStratum returns the IsUsingFallbackStratum field value
func (o *SystemInfo) GetIsUsingFallbackStratum() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.IsUsingFallbackStratum
}

// GetIsUsingFallbackStratumOk returns a tuple with the IsUsingFallbackStratum field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetIsUsingFallbackStratumOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsUsingFallbackStratum, true
}

// SetIsUsingFallbackStratum sets field value
func (o *SystemInfo) SetIsUsingFallbackStratum(v float32) {
	o.IsUsingFallbackStratum = v
}

// GetMacAddr returns the MacAddr field value
func (o *SystemInfo) GetMacAddr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MacAddr
}

// GetMacAddrOk returns a tuple with the MacAddr field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetMacAddrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MacAddr, true
}

// SetMacAddr sets field value
func (o *SystemInfo) SetMacAddr(v string) {
	o.MacAddr = v
}

// GetManualFanSpeed returns the ManualFanSpeed field value
func (o *SystemInfo) GetManualFanSpeed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ManualFanSpeed
}

// GetManualFanSpeedOk returns a tuple with the ManualFanSpeed field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetManualFanSpeedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManualFanSpeed, true
}

// SetManualFanSpeed sets field value
func (o *SystemInfo) SetManualFanSpeed(v int32) {
	o.ManualFanSpeed = v
}

// GetMaxPower returns the MaxPower field value
func (o *SystemInfo) GetMaxPower() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxPower
}

// GetMaxPowerOk returns a tuple with the MaxPower field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetMaxPowerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxPower, true
}

// SetMaxPower sets field value
func (o *SystemInfo) SetMaxPower(v int32) {
	o.MaxPower = v
}

// GetMinFanSpeed returns the MinFanSpeed field value
func (o *SystemInfo) GetMinFanSpeed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinFanSpeed
}

// GetMinFanSpeedOk returns a tuple with the MinFanSpeed field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetMinFanSpeedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinFanSpeed, true
}

// SetMinFanSpeed sets field value
func (o *SystemInfo) SetMinFanSpeed(v int32) {
	o.MinFanSpeed = v
}

// GetNominalVoltage returns the NominalVoltage field value
func (o *SystemInfo) GetNominalVoltage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NominalVoltage
}

// GetNominalVoltageOk returns a tuple with the NominalVoltage field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetNominalVoltageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NominalVoltage, true
}

// SetNominalVoltage sets field value
func (o *SystemInfo) SetNominalVoltage(v int32) {
	o.NominalVoltage = v
}

// GetOverheatMode returns the OverheatMode field value
func (o *SystemInfo) GetOverheatMode() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.OverheatMode
}

// GetOverheatModeOk returns a tuple with the OverheatMode field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetOverheatModeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverheatMode, true
}

// SetOverheatMode sets field value
func (o *SystemInfo) SetOverheatMode(v float32) {
	o.OverheatMode = v
}

// GetOverclockEnabled returns the OverclockEnabled field value
func (o *SystemInfo) GetOverclockEnabled() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OverclockEnabled
}

// GetOverclockEnabledOk returns a tuple with the OverclockEnabled field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetOverclockEnabledOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverclockEnabled, true
}

// SetOverclockEnabled sets field value
func (o *SystemInfo) SetOverclockEnabled(v int32) {
	o.OverclockEnabled = v
}

// GetPoolConnectionInfo returns the PoolConnectionInfo field value
func (o *SystemInfo) GetPoolConnectionInfo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolConnectionInfo
}

// GetPoolConnectionInfoOk returns a tuple with the PoolConnectionInfo field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetPoolConnectionInfoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolConnectionInfo, true
}

// SetPoolConnectionInfo sets field value
func (o *SystemInfo) SetPoolConnectionInfo(v string) {
	o.PoolConnectionInfo = v
}

// GetPoolDifficulty returns the PoolDifficulty field value
func (o *SystemInfo) GetPoolDifficulty() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PoolDifficulty
}

// GetPoolDifficultyOk returns a tuple with the PoolDifficulty field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetPoolDifficultyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolDifficulty, true
}

// SetPoolDifficulty sets field value
func (o *SystemInfo) SetPoolDifficulty(v float32) {
	o.PoolDifficulty = v
}

// GetPower returns the Power field value
func (o *SystemInfo) GetPower() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Power
}

// GetPowerOk returns a tuple with the Power field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetPowerOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Power, true
}

// SetPower sets field value
func (o *SystemInfo) SetPower(v float32) {
	o.Power = v
}

// GetPowerFault returns the PowerFault field value if set, zero value otherwise.
func (o *SystemInfo) GetPowerFault() string {
	if o == nil || IsNil(o.PowerFault) {
		var ret string
		return ret
	}
	return *o.PowerFault
}

// GetPowerFaultOk returns a tuple with the PowerFault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetPowerFaultOk() (*string, bool) {
	if o == nil || IsNil(o.PowerFault) {
		return nil, false
	}
	return o.PowerFault, true
}

// HasPowerFault returns a boolean if a field has been set.
func (o *SystemInfo) HasPowerFault() bool {
	if o != nil && !IsNil(o.PowerFault) {
		return true
	}

	return false
}

// SetPowerFault gets a reference to the given string and assigns it to the PowerFault field.
func (o *SystemInfo) SetPowerFault(v string) {
	o.PowerFault = &v
}

// GetResetReason returns the ResetReason field value
func (o *SystemInfo) GetResetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResetReason
}

// GetResetReasonOk returns a tuple with the ResetReason field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetResetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResetReason, true
}

// SetResetReason sets field value
func (o *SystemInfo) SetResetReason(v string) {
	o.ResetReason = v
}

// GetRunningPartition returns the RunningPartition field value
func (o *SystemInfo) GetRunningPartition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RunningPartition
}

// GetRunningPartitionOk returns a tuple with the RunningPartition field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetRunningPartitionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunningPartition, true
}

// SetRunningPartition sets field value
func (o *SystemInfo) SetRunningPartition(v string) {
	o.RunningPartition = v
}

// GetSharesAccepted returns the SharesAccepted field value
func (o *SystemInfo) GetSharesAccepted() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SharesAccepted
}

// GetSharesAcceptedOk returns a tuple with the SharesAccepted field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetSharesAcceptedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SharesAccepted, true
}

// SetSharesAccepted sets field value
func (o *SystemInfo) SetSharesAccepted(v float32) {
	o.SharesAccepted = v
}

// GetSharesRejected returns the SharesRejected field value
func (o *SystemInfo) GetSharesRejected() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SharesRejected
}

// GetSharesRejectedOk returns a tuple with the SharesRejected field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetSharesRejectedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SharesRejected, true
}

// SetSharesRejected sets field value
func (o *SystemInfo) SetSharesRejected(v float32) {
	o.SharesRejected = v
}

// GetSharesRejectedReasons returns the SharesRejectedReasons field value
func (o *SystemInfo) GetSharesRejectedReasons() []SharesRejectedReason {
	if o == nil {
		var ret []SharesRejectedReason
		return ret
	}

	return o.SharesRejectedReasons
}

// GetSharesRejectedReasonsOk returns a tuple with the SharesRejectedReasons field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetSharesRejectedReasonsOk() ([]SharesRejectedReason, bool) {
	if o == nil {
		return nil, false
	}
	return o.SharesRejectedReasons, true
}

// SetSharesRejectedReasons sets field value
func (o *SystemInfo) SetSharesRejectedReasons(v []SharesRejectedReason) {
	o.SharesRejectedReasons = v
}

// GetSmallCoreCount returns the SmallCoreCount field value
func (o *SystemInfo) GetSmallCoreCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SmallCoreCount
}

// GetSmallCoreCountOk returns a tuple with the SmallCoreCount field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetSmallCoreCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SmallCoreCount, true
}

// SetSmallCoreCount sets field value
func (o *SystemInfo) SetSmallCoreCount(v float32) {
	o.SmallCoreCount = v
}

// GetSsid returns the Ssid field value
func (o *SystemInfo) GetSsid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ssid
}

// GetSsidOk returns a tuple with the Ssid field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetSsidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ssid, true
}

// SetSsid sets field value
func (o *SystemInfo) SetSsid(v string) {
	o.Ssid = v
}

// GetIpv4 returns the Ipv4 field value
func (o *SystemInfo) GetIpv4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv4
}

// GetIpv4Ok returns a tuple with the Ipv4 field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetIpv4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv4, true
}

// SetIpv4 sets field value
func (o *SystemInfo) SetIpv4(v string) {
	o.Ipv4 = v
}

// GetIpv6 returns the Ipv6 field value
func (o *SystemInfo) GetIpv6() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv6
}

// GetIpv6Ok returns a tuple with the Ipv6 field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetIpv6Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv6, true
}

// SetIpv6 sets field value
func (o *SystemInfo) SetIpv6(v string) {
	o.Ipv6 = v
}

// GetStratumExtranonceSubscribe returns the StratumExtranonceSubscribe field value
func (o *SystemInfo) GetStratumExtranonceSubscribe() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.StratumExtranonceSubscribe
}

// GetStratumExtranonceSubscribeOk returns a tuple with the StratumExtranonceSubscribe field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetStratumExtranonceSubscribeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StratumExtranonceSubscribe, true
}

// SetStratumExtranonceSubscribe sets field value
func (o *SystemInfo) SetStratumExtranonceSubscribe(v bool) {
	o.StratumExtranonceSubscribe = v
}

// GetStratumPort returns the StratumPort field value
func (o *SystemInfo) GetStratumPort() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StratumPort
}

// GetStratumPortOk returns a tuple with the StratumPort field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetStratumPortOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StratumPort, true
}

// SetStratumPort sets field value
func (o *SystemInfo) SetStratumPort(v float32) {
	o.StratumPort = v
}

// GetStratumSuggestedDifficulty returns the StratumSuggestedDifficulty field value
func (o *SystemInfo) GetStratumSuggestedDifficulty() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StratumSuggestedDifficulty
}

// GetStratumSuggestedDifficultyOk returns a tuple with the StratumSuggestedDifficulty field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetStratumSuggestedDifficultyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StratumSuggestedDifficulty, true
}

// SetStratumSuggestedDifficulty sets field value
func (o *SystemInfo) SetStratumSuggestedDifficulty(v float32) {
	o.StratumSuggestedDifficulty = v
}

// GetStratumURL returns the StratumURL field value
func (o *SystemInfo) GetStratumURL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StratumURL
}

// GetStratumURLOk returns a tuple with the StratumURL field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetStratumURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StratumURL, true
}

// SetStratumURL sets field value
func (o *SystemInfo) SetStratumURL(v string) {
	o.StratumURL = v
}

// GetStratumUser returns the StratumUser field value
func (o *SystemInfo) GetStratumUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StratumUser
}

// GetStratumUserOk returns a tuple with the StratumUser field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetStratumUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StratumUser, true
}

// SetStratumUser sets field value
func (o *SystemInfo) SetStratumUser(v string) {
	o.StratumUser = v
}

// GetStratumTLS returns the StratumTLS field value
func (o *SystemInfo) GetStratumTLS() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.StratumTLS
}

// GetStratumTLSOk returns a tuple with the StratumTLS field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetStratumTLSOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StratumTLS, true
}

// SetStratumTLS sets field value
func (o *SystemInfo) SetStratumTLS(v bool) {
	o.StratumTLS = v
}

// GetStratumCert returns the StratumCert field value
func (o *SystemInfo) GetStratumCert() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StratumCert
}

// GetStratumCertOk returns a tuple with the StratumCert field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetStratumCertOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StratumCert, true
}

// SetStratumCert sets field value
func (o *SystemInfo) SetStratumCert(v string) {
	o.StratumCert = v
}

// GetTemp returns the Temp field value
func (o *SystemInfo) GetTemp() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Temp
}

// GetTempOk returns a tuple with the Temp field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetTempOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Temp, true
}

// SetTemp sets field value
func (o *SystemInfo) SetTemp(v float32) {
	o.Temp = v
}

// GetTemp2 returns the Temp2 field value
func (o *SystemInfo) GetTemp2() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Temp2
}

// GetTemp2Ok returns a tuple with the Temp2 field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetTemp2Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Temp2, true
}

// SetTemp2 sets field value
func (o *SystemInfo) SetTemp2(v float32) {
	o.Temp2 = v
}

// GetUptimeSeconds returns the UptimeSeconds field value
func (o *SystemInfo) GetUptimeSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.UptimeSeconds
}

// GetUptimeSecondsOk returns a tuple with the UptimeSeconds field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetUptimeSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UptimeSeconds, true
}

// SetUptimeSeconds sets field value
func (o *SystemInfo) SetUptimeSeconds(v float32) {
	o.UptimeSeconds = v
}

// GetVersion returns the Version field value
func (o *SystemInfo) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *SystemInfo) SetVersion(v string) {
	o.Version = v
}

// GetAxeOSVersion returns the AxeOSVersion field value
func (o *SystemInfo) GetAxeOSVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AxeOSVersion
}

// GetAxeOSVersionOk returns a tuple with the AxeOSVersion field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetAxeOSVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AxeOSVersion, true
}

// SetAxeOSVersion sets field value
func (o *SystemInfo) SetAxeOSVersion(v string) {
	o.AxeOSVersion = v
}

// GetVoltage returns the Voltage field value
func (o *SystemInfo) GetVoltage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Voltage
}

// GetVoltageOk returns a tuple with the Voltage field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetVoltageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Voltage, true
}

// SetVoltage sets field value
func (o *SystemInfo) SetVoltage(v float32) {
	o.Voltage = v
}

// GetVrTemp returns the VrTemp field value
func (o *SystemInfo) GetVrTemp() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.VrTemp
}

// GetVrTempOk returns a tuple with the VrTemp field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetVrTempOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VrTemp, true
}

// SetVrTemp sets field value
func (o *SystemInfo) SetVrTemp(v float32) {
	o.VrTemp = v
}

// GetWifiStatus returns the WifiStatus field value
func (o *SystemInfo) GetWifiStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WifiStatus
}

// GetWifiStatusOk returns a tuple with the WifiStatus field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetWifiStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WifiStatus, true
}

// SetWifiStatus sets field value
func (o *SystemInfo) SetWifiStatus(v string) {
	o.WifiStatus = v
}

// GetWifiRSSI returns the WifiRSSI field value
func (o *SystemInfo) GetWifiRSSI() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.WifiRSSI
}

// GetWifiRSSIOk returns a tuple with the WifiRSSI field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetWifiRSSIOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WifiRSSI, true
}

// SetWifiRSSI sets field value
func (o *SystemInfo) SetWifiRSSI(v float32) {
	o.WifiRSSI = v
}

// GetDisplayTimeout returns the DisplayTimeout field value
func (o *SystemInfo) GetDisplayTimeout() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DisplayTimeout
}

// GetDisplayTimeoutOk returns a tuple with the DisplayTimeout field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetDisplayTimeoutOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayTimeout, true
}

// SetDisplayTimeout sets field value
func (o *SystemInfo) SetDisplayTimeout(v float32) {
	o.DisplayTimeout = v
}

// GetStatsFrequency returns the StatsFrequency field value
func (o *SystemInfo) GetStatsFrequency() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StatsFrequency
}

// GetStatsFrequencyOk returns a tuple with the StatsFrequency field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetStatsFrequencyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatsFrequency, true
}

// SetStatsFrequency sets field value
func (o *SystemInfo) SetStatsFrequency(v float32) {
	o.StatsFrequency = v
}

// GetBlockHeight returns the BlockHeight field value
func (o *SystemInfo) GetBlockHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlockHeight
}

// GetBlockHeightOk returns a tuple with the BlockHeight field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetBlockHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockHeight, true
}

// SetBlockHeight sets field value
func (o *SystemInfo) SetBlockHeight(v int32) {
	o.BlockHeight = v
}

// GetScriptsig returns the Scriptsig field value
func (o *SystemInfo) GetScriptsig() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scriptsig
}

// GetScriptsigOk returns a tuple with the Scriptsig field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetScriptsigOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scriptsig, true
}

// SetScriptsig sets field value
func (o *SystemInfo) SetScriptsig(v string) {
	o.Scriptsig = v
}

// GetNetworkDifficulty returns the NetworkDifficulty field value
func (o *SystemInfo) GetNetworkDifficulty() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.NetworkDifficulty
}

// GetNetworkDifficultyOk returns a tuple with the NetworkDifficulty field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetNetworkDifficultyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkDifficulty, true
}

// SetNetworkDifficulty sets field value
func (o *SystemInfo) SetNetworkDifficulty(v float32) {
	o.NetworkDifficulty = v
}

// GetBlockFound returns the BlockFound field value
func (o *SystemInfo) GetBlockFound() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BlockFound
}

// GetBlockFoundOk returns a tuple with the BlockFound field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetBlockFoundOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockFound, true
}

// SetBlockFound sets field value
func (o *SystemInfo) SetBlockFound(v float32) {
	o.BlockFound = v
}

// GetHashrateMonitor returns the HashrateMonitor field value
func (o *SystemInfo) GetHashrateMonitor() SystemInfoHashrateMonitor {
	if o == nil {
		var ret SystemInfoHashrateMonitor
		return ret
	}

	return o.HashrateMonitor
}

// GetHashrateMonitorOk returns a tuple with the HashrateMonitor field value
// and a boolean to check if the value has been set.
func (o *SystemInfo) GetHashrateMonitorOk() (*SystemInfoHashrateMonitor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HashrateMonitor, true
}

// SetHashrateMonitor sets field value
func (o *SystemInfo) SetHashrateMonitor(v SystemInfoHashrateMonitor) {
	o.HashrateMonitor = v
}

func (o SystemInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ASICModel"] = o.ASICModel
	toSerialize["apEnabled"] = o.ApEnabled
	toSerialize["autofanspeed"] = o.Autofanspeed
	toSerialize["bestDiff"] = o.BestDiff
	toSerialize["bestSessionDiff"] = o.BestSessionDiff
	toSerialize["boardVersion"] = o.BoardVersion
	toSerialize["coreVoltage"] = o.CoreVoltage
	toSerialize["coreVoltageActual"] = o.CoreVoltageActual
	toSerialize["current"] = o.Current
	toSerialize["display"] = o.Display
	toSerialize["fallbackStratumExtranonceSubscribe"] = o.FallbackStratumExtranonceSubscribe
	toSerialize["fallbackStratumPort"] = o.FallbackStratumPort
	toSerialize["fallbackStratumSuggestedDifficulty"] = o.FallbackStratumSuggestedDifficulty
	toSerialize["fallbackStratumURL"] = o.FallbackStratumURL
	toSerialize["fallbackStratumUser"] = o.FallbackStratumUser
	toSerialize["fallbackStratumTLS"] = o.FallbackStratumTLS
	toSerialize["fallbackStratumCert"] = o.FallbackStratumCert
	toSerialize["fanrpm"] = o.Fanrpm
	toSerialize["fan2rpm"] = o.Fan2rpm
	toSerialize["fanspeed"] = o.Fanspeed
	toSerialize["temptarget"] = o.Temptarget
	toSerialize["responseTime"] = o.ResponseTime
	toSerialize["rotation"] = o.Rotation
	toSerialize["freeHeap"] = o.FreeHeap
	toSerialize["freeHeapInternal"] = o.FreeHeapInternal
	toSerialize["freeHeapSpiram"] = o.FreeHeapSpiram
	toSerialize["frequency"] = o.Frequency
	toSerialize["hashRate"] = o.HashRate
	toSerialize["hashRate_1m"] = o.HashRate1m
	toSerialize["hashRate_10m"] = o.HashRate10m
	toSerialize["hashRate_1h"] = o.HashRate1h
	toSerialize["expectedHashrate"] = o.ExpectedHashrate
	toSerialize["errorPercentage"] = o.ErrorPercentage
	toSerialize["hostname"] = o.Hostname
	toSerialize["idfVersion"] = o.IdfVersion
	toSerialize["invertscreen"] = o.Invertscreen
	toSerialize["isPSRAMAvailable"] = o.IsPSRAMAvailable
	toSerialize["isUsingFallbackStratum"] = o.IsUsingFallbackStratum
	toSerialize["macAddr"] = o.MacAddr
	toSerialize["manualFanSpeed"] = o.ManualFanSpeed
	toSerialize["maxPower"] = o.MaxPower
	toSerialize["minFanSpeed"] = o.MinFanSpeed
	toSerialize["nominalVoltage"] = o.NominalVoltage
	toSerialize["overheat_mode"] = o.OverheatMode
	toSerialize["overclockEnabled"] = o.OverclockEnabled
	toSerialize["poolConnectionInfo"] = o.PoolConnectionInfo
	toSerialize["poolDifficulty"] = o.PoolDifficulty
	toSerialize["power"] = o.Power
	if !IsNil(o.PowerFault) {
		toSerialize["power_fault"] = o.PowerFault
	}
	toSerialize["resetReason"] = o.ResetReason
	toSerialize["runningPartition"] = o.RunningPartition
	toSerialize["sharesAccepted"] = o.SharesAccepted
	toSerialize["sharesRejected"] = o.SharesRejected
	toSerialize["sharesRejectedReasons"] = o.SharesRejectedReasons
	toSerialize["smallCoreCount"] = o.SmallCoreCount
	toSerialize["ssid"] = o.Ssid
	toSerialize["ipv4"] = o.Ipv4
	toSerialize["ipv6"] = o.Ipv6
	toSerialize["stratumExtranonceSubscribe"] = o.StratumExtranonceSubscribe
	toSerialize["stratumPort"] = o.StratumPort
	toSerialize["stratumSuggestedDifficulty"] = o.StratumSuggestedDifficulty
	toSerialize["stratumURL"] = o.StratumURL
	toSerialize["stratumUser"] = o.StratumUser
	toSerialize["stratumTLS"] = o.StratumTLS
	toSerialize["stratumCert"] = o.StratumCert
	toSerialize["temp"] = o.Temp
	toSerialize["temp2"] = o.Temp2
	toSerialize["uptimeSeconds"] = o.UptimeSeconds
	toSerialize["version"] = o.Version
	toSerialize["axeOSVersion"] = o.AxeOSVersion
	toSerialize["voltage"] = o.Voltage
	toSerialize["vrTemp"] = o.VrTemp
	toSerialize["wifiStatus"] = o.WifiStatus
	toSerialize["wifiRSSI"] = o.WifiRSSI
	toSerialize["displayTimeout"] = o.DisplayTimeout
	toSerialize["statsFrequency"] = o.StatsFrequency
	toSerialize["blockHeight"] = o.BlockHeight
	toSerialize["scriptsig"] = o.Scriptsig
	toSerialize["networkDifficulty"] = o.NetworkDifficulty
	toSerialize["blockFound"] = o.BlockFound
	toSerialize["hashrateMonitor"] = o.HashrateMonitor
	return toSerialize, nil
}

func (o *SystemInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ASICModel",
		"apEnabled",
		"autofanspeed",
		"bestDiff",
		"bestSessionDiff",
		"boardVersion",
		"coreVoltage",
		"coreVoltageActual",
		"current",
		"display",
		"fallbackStratumExtranonceSubscribe",
		"fallbackStratumPort",
		"fallbackStratumSuggestedDifficulty",
		"fallbackStratumURL",
		"fallbackStratumUser",
		"fallbackStratumTLS",
		"fallbackStratumCert",
		"fanrpm",
		"fan2rpm",
		"fanspeed",
		"temptarget",
		"responseTime",
		"rotation",
		"freeHeap",
		"freeHeapInternal",
		"freeHeapSpiram",
		"frequency",
		"hashRate",
		"hashRate_1m",
		"hashRate_10m",
		"hashRate_1h",
		"expectedHashrate",
		"errorPercentage",
		"hostname",
		"idfVersion",
		"invertscreen",
		"isPSRAMAvailable",
		"isUsingFallbackStratum",
		"macAddr",
		"manualFanSpeed",
		"maxPower",
		"minFanSpeed",
		"nominalVoltage",
		"overheat_mode",
		"overclockEnabled",
		"poolConnectionInfo",
		"poolDifficulty",
		"power",
		"resetReason",
		"runningPartition",
		"sharesAccepted",
		"sharesRejected",
		"sharesRejectedReasons",
		"smallCoreCount",
		"ssid",
		"ipv4",
		"ipv6",
		"stratumExtranonceSubscribe",
		"stratumPort",
		"stratumSuggestedDifficulty",
		"stratumURL",
		"stratumUser",
		"stratumTLS",
		"stratumCert",
		"temp",
		"temp2",
		"uptimeSeconds",
		"version",
		"axeOSVersion",
		"voltage",
		"vrTemp",
		"wifiStatus",
		"wifiRSSI",
		"displayTimeout",
		"statsFrequency",
		"blockHeight",
		"scriptsig",
		"networkDifficulty",
		"blockFound",
		"hashrateMonitor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemInfo := _SystemInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemInfo)

	if err != nil {
		return err
	}

	*o = SystemInfo(varSystemInfo)

	return err
}

type NullableSystemInfo struct {
	value *SystemInfo
	isSet bool
}

func (v NullableSystemInfo) Get() *SystemInfo {
	return v.value
}

func (v *NullableSystemInfo) Set(val *SystemInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemInfo(val *SystemInfo) *NullableSystemInfo {
	return &NullableSystemInfo{value: val, isSet: true}
}

func (v NullableSystemInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


