/*
ESP-Miner API

API specification for ESP-Miner HTTP server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemASIC type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemASIC{}

// SystemASIC struct for SystemASIC
type SystemASIC struct {
	// ASIC model identifier
	ASICModel string `json:"ASICModel"`
	// Device model name
	DeviceModel string `json:"deviceModel"`
	// Swarm color
	SwarmColor string `json:"swarmColor"`
	// Number of ASICs detected
	AsicCount float32 `json:"asicCount"`
	// Default frequency for the ASIC model in MHz
	DefaultFrequency float32 `json:"defaultFrequency"`
	// Available frequency options for the ASIC model in MHz
	FrequencyOptions []float32 `json:"frequencyOptions"`
	// Default voltage for the ASIC model in millivolts
	DefaultVoltage float32 `json:"defaultVoltage"`
	// Available voltage options for the ASIC model in millivolts
	VoltageOptions []float32 `json:"voltageOptions"`
}

type _SystemASIC SystemASIC

// NewSystemASIC instantiates a new SystemASIC object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemASIC(aSICModel string, deviceModel string, swarmColor string, asicCount float32, defaultFrequency float32, frequencyOptions []float32, defaultVoltage float32, voltageOptions []float32) *SystemASIC {
	this := SystemASIC{}
	this.ASICModel = aSICModel
	this.DeviceModel = deviceModel
	this.SwarmColor = swarmColor
	this.AsicCount = asicCount
	this.DefaultFrequency = defaultFrequency
	this.FrequencyOptions = frequencyOptions
	this.DefaultVoltage = defaultVoltage
	this.VoltageOptions = voltageOptions
	return &this
}

// NewSystemASICWithDefaults instantiates a new SystemASIC object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemASICWithDefaults() *SystemASIC {
	this := SystemASIC{}
	return &this
}

// GetASICModel returns the ASICModel field value
func (o *SystemASIC) GetASICModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ASICModel
}

// GetASICModelOk returns a tuple with the ASICModel field value
// and a boolean to check if the value has been set.
func (o *SystemASIC) GetASICModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ASICModel, true
}

// SetASICModel sets field value
func (o *SystemASIC) SetASICModel(v string) {
	o.ASICModel = v
}

// GetDeviceModel returns the DeviceModel field value
func (o *SystemASIC) GetDeviceModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceModel
}

// GetDeviceModelOk returns a tuple with the DeviceModel field value
// and a boolean to check if the value has been set.
func (o *SystemASIC) GetDeviceModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceModel, true
}

// SetDeviceModel sets field value
func (o *SystemASIC) SetDeviceModel(v string) {
	o.DeviceModel = v
}

// GetSwarmColor returns the SwarmColor field value
func (o *SystemASIC) GetSwarmColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SwarmColor
}

// GetSwarmColorOk returns a tuple with the SwarmColor field value
// and a boolean to check if the value has been set.
func (o *SystemASIC) GetSwarmColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwarmColor, true
}

// SetSwarmColor sets field value
func (o *SystemASIC) SetSwarmColor(v string) {
	o.SwarmColor = v
}

// GetAsicCount returns the AsicCount field value
func (o *SystemASIC) GetAsicCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AsicCount
}

// GetAsicCountOk returns a tuple with the AsicCount field value
// and a boolean to check if the value has been set.
func (o *SystemASIC) GetAsicCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AsicCount, true
}

// SetAsicCount sets field value
func (o *SystemASIC) SetAsicCount(v float32) {
	o.AsicCount = v
}

// GetDefaultFrequency returns the DefaultFrequency field value
func (o *SystemASIC) GetDefaultFrequency() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DefaultFrequency
}

// GetDefaultFrequencyOk returns a tuple with the DefaultFrequency field value
// and a boolean to check if the value has been set.
func (o *SystemASIC) GetDefaultFrequencyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultFrequency, true
}

// SetDefaultFrequency sets field value
func (o *SystemASIC) SetDefaultFrequency(v float32) {
	o.DefaultFrequency = v
}

// GetFrequencyOptions returns the FrequencyOptions field value
func (o *SystemASIC) GetFrequencyOptions() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.FrequencyOptions
}

// GetFrequencyOptionsOk returns a tuple with the FrequencyOptions field value
// and a boolean to check if the value has been set.
func (o *SystemASIC) GetFrequencyOptionsOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FrequencyOptions, true
}

// SetFrequencyOptions sets field value
func (o *SystemASIC) SetFrequencyOptions(v []float32) {
	o.FrequencyOptions = v
}

// GetDefaultVoltage returns the DefaultVoltage field value
func (o *SystemASIC) GetDefaultVoltage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DefaultVoltage
}

// GetDefaultVoltageOk returns a tuple with the DefaultVoltage field value
// and a boolean to check if the value has been set.
func (o *SystemASIC) GetDefaultVoltageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultVoltage, true
}

// SetDefaultVoltage sets field value
func (o *SystemASIC) SetDefaultVoltage(v float32) {
	o.DefaultVoltage = v
}

// GetVoltageOptions returns the VoltageOptions field value
func (o *SystemASIC) GetVoltageOptions() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.VoltageOptions
}

// GetVoltageOptionsOk returns a tuple with the VoltageOptions field value
// and a boolean to check if the value has been set.
func (o *SystemASIC) GetVoltageOptionsOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoltageOptions, true
}

// SetVoltageOptions sets field value
func (o *SystemASIC) SetVoltageOptions(v []float32) {
	o.VoltageOptions = v
}

func (o SystemASIC) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemASIC) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ASICModel"] = o.ASICModel
	toSerialize["deviceModel"] = o.DeviceModel
	toSerialize["swarmColor"] = o.SwarmColor
	toSerialize["asicCount"] = o.AsicCount
	toSerialize["defaultFrequency"] = o.DefaultFrequency
	toSerialize["frequencyOptions"] = o.FrequencyOptions
	toSerialize["defaultVoltage"] = o.DefaultVoltage
	toSerialize["voltageOptions"] = o.VoltageOptions
	return toSerialize, nil
}

func (o *SystemASIC) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ASICModel",
		"deviceModel",
		"swarmColor",
		"asicCount",
		"defaultFrequency",
		"frequencyOptions",
		"defaultVoltage",
		"voltageOptions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemASIC := _SystemASIC{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemASIC)

	if err != nil {
		return err
	}

	*o = SystemASIC(varSystemASIC)

	return err
}

type NullableSystemASIC struct {
	value *SystemASIC
	isSet bool
}

func (v NullableSystemASIC) Get() *SystemASIC {
	return v.value
}

func (v *NullableSystemASIC) Set(val *SystemASIC) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemASIC) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemASIC) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemASIC(val *SystemASIC) *NullableSystemASIC {
	return &NullableSystemASIC{value: val, isSet: true}
}

func (v NullableSystemASIC) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemASIC) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


