/*
ESP-Miner API

API specification for ESP-Miner HTTP server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemInfoHashrateMonitor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemInfoHashrateMonitor{}

// SystemInfoHashrateMonitor struct for SystemInfoHashrateMonitor
type SystemInfoHashrateMonitor struct {
	// Hashrate register value per ASIC
	Asics []HashrateMonitorAsic `json:"asics"`
}

type _SystemInfoHashrateMonitor SystemInfoHashrateMonitor

// NewSystemInfoHashrateMonitor instantiates a new SystemInfoHashrateMonitor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemInfoHashrateMonitor(asics []HashrateMonitorAsic) *SystemInfoHashrateMonitor {
	this := SystemInfoHashrateMonitor{}
	this.Asics = asics
	return &this
}

// NewSystemInfoHashrateMonitorWithDefaults instantiates a new SystemInfoHashrateMonitor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemInfoHashrateMonitorWithDefaults() *SystemInfoHashrateMonitor {
	this := SystemInfoHashrateMonitor{}
	return &this
}

// GetAsics returns the Asics field value
func (o *SystemInfoHashrateMonitor) GetAsics() []HashrateMonitorAsic {
	if o == nil {
		var ret []HashrateMonitorAsic
		return ret
	}

	return o.Asics
}

// GetAsicsOk returns a tuple with the Asics field value
// and a boolean to check if the value has been set.
func (o *SystemInfoHashrateMonitor) GetAsicsOk() ([]HashrateMonitorAsic, bool) {
	if o == nil {
		return nil, false
	}
	return o.Asics, true
}

// SetAsics sets field value
func (o *SystemInfoHashrateMonitor) SetAsics(v []HashrateMonitorAsic) {
	o.Asics = v
}

func (o SystemInfoHashrateMonitor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemInfoHashrateMonitor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asics"] = o.Asics
	return toSerialize, nil
}

func (o *SystemInfoHashrateMonitor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asics",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemInfoHashrateMonitor := _SystemInfoHashrateMonitor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemInfoHashrateMonitor)

	if err != nil {
		return err
	}

	*o = SystemInfoHashrateMonitor(varSystemInfoHashrateMonitor)

	return err
}

type NullableSystemInfoHashrateMonitor struct {
	value *SystemInfoHashrateMonitor
	isSet bool
}

func (v NullableSystemInfoHashrateMonitor) Get() *SystemInfoHashrateMonitor {
	return v.value
}

func (v *NullableSystemInfoHashrateMonitor) Set(val *SystemInfoHashrateMonitor) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemInfoHashrateMonitor) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemInfoHashrateMonitor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemInfoHashrateMonitor(val *SystemInfoHashrateMonitor) *NullableSystemInfoHashrateMonitor {
	return &NullableSystemInfoHashrateMonitor{value: val, isSet: true}
}

func (v NullableSystemInfoHashrateMonitor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemInfoHashrateMonitor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


