/*
ESP-Miner API

API specification for ESP-Miner HTTP server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SharesRejectedReason type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SharesRejectedReason{}

// SharesRejectedReason struct for SharesRejectedReason
type SharesRejectedReason struct {
	// Rejection reason from pool
	Message string `json:"message"`
	// Shares rejected for this reason
	Count int32 `json:"count"`
}

type _SharesRejectedReason SharesRejectedReason

// NewSharesRejectedReason instantiates a new SharesRejectedReason object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharesRejectedReason(message string, count int32) *SharesRejectedReason {
	this := SharesRejectedReason{}
	this.Message = message
	this.Count = count
	return &this
}

// NewSharesRejectedReasonWithDefaults instantiates a new SharesRejectedReason object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharesRejectedReasonWithDefaults() *SharesRejectedReason {
	this := SharesRejectedReason{}
	return &this
}

// GetMessage returns the Message field value
func (o *SharesRejectedReason) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SharesRejectedReason) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SharesRejectedReason) SetMessage(v string) {
	o.Message = v
}

// GetCount returns the Count field value
func (o *SharesRejectedReason) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *SharesRejectedReason) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *SharesRejectedReason) SetCount(v int32) {
	o.Count = v
}

func (o SharesRejectedReason) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SharesRejectedReason) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *SharesRejectedReason) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSharesRejectedReason := _SharesRejectedReason{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSharesRejectedReason)

	if err != nil {
		return err
	}

	*o = SharesRejectedReason(varSharesRejectedReason)

	return err
}

type NullableSharesRejectedReason struct {
	value *SharesRejectedReason
	isSet bool
}

func (v NullableSharesRejectedReason) Get() *SharesRejectedReason {
	return v.value
}

func (v *NullableSharesRejectedReason) Set(val *SharesRejectedReason) {
	v.value = val
	v.isSet = true
}

func (v NullableSharesRejectedReason) IsSet() bool {
	return v.isSet
}

func (v *NullableSharesRejectedReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharesRejectedReason(val *SharesRejectedReason) *NullableSharesRejectedReason {
	return &NullableSharesRejectedReason{value: val, isSet: true}
}

func (v NullableSharesRejectedReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharesRejectedReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


