/*
ESP-Miner API

API specification for ESP-Miner HTTP server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HashrateMonitorAsic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HashrateMonitorAsic{}

// HashrateMonitorAsic struct for HashrateMonitorAsic
type HashrateMonitorAsic struct {
	// Hashrate
	Total float32 `json:"total"`
	// Hashrate per domain
	Domains []float32 `json:"domains"`
	// Number of errors
	ErrorCount float32 `json:"errorCount"`
}

type _HashrateMonitorAsic HashrateMonitorAsic

// NewHashrateMonitorAsic instantiates a new HashrateMonitorAsic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHashrateMonitorAsic(total float32, domains []float32, errorCount float32) *HashrateMonitorAsic {
	this := HashrateMonitorAsic{}
	this.Total = total
	this.Domains = domains
	this.ErrorCount = errorCount
	return &this
}

// NewHashrateMonitorAsicWithDefaults instantiates a new HashrateMonitorAsic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHashrateMonitorAsicWithDefaults() *HashrateMonitorAsic {
	this := HashrateMonitorAsic{}
	return &this
}

// GetTotal returns the Total field value
func (o *HashrateMonitorAsic) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *HashrateMonitorAsic) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *HashrateMonitorAsic) SetTotal(v float32) {
	o.Total = v
}

// GetDomains returns the Domains field value
func (o *HashrateMonitorAsic) GetDomains() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value
// and a boolean to check if the value has been set.
func (o *HashrateMonitorAsic) GetDomainsOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domains, true
}

// SetDomains sets field value
func (o *HashrateMonitorAsic) SetDomains(v []float32) {
	o.Domains = v
}

// GetErrorCount returns the ErrorCount field value
func (o *HashrateMonitorAsic) GetErrorCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ErrorCount
}

// GetErrorCountOk returns a tuple with the ErrorCount field value
// and a boolean to check if the value has been set.
func (o *HashrateMonitorAsic) GetErrorCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorCount, true
}

// SetErrorCount sets field value
func (o *HashrateMonitorAsic) SetErrorCount(v float32) {
	o.ErrorCount = v
}

func (o HashrateMonitorAsic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HashrateMonitorAsic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["domains"] = o.Domains
	toSerialize["errorCount"] = o.ErrorCount
	return toSerialize, nil
}

func (o *HashrateMonitorAsic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"domains",
		"errorCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHashrateMonitorAsic := _HashrateMonitorAsic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHashrateMonitorAsic)

	if err != nil {
		return err
	}

	*o = HashrateMonitorAsic(varHashrateMonitorAsic)

	return err
}

type NullableHashrateMonitorAsic struct {
	value *HashrateMonitorAsic
	isSet bool
}

func (v NullableHashrateMonitorAsic) Get() *HashrateMonitorAsic {
	return v.value
}

func (v *NullableHashrateMonitorAsic) Set(val *HashrateMonitorAsic) {
	v.value = val
	v.isSet = true
}

func (v NullableHashrateMonitorAsic) IsSet() bool {
	return v.isSet
}

func (v *NullableHashrateMonitorAsic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHashrateMonitorAsic(val *HashrateMonitorAsic) *NullableHashrateMonitorAsic {
	return &NullableHashrateMonitorAsic{value: val, isSet: true}
}

func (v NullableHashrateMonitorAsic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHashrateMonitorAsic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


